// 
// Decompiled by Procyon v0.5.30
// 

package org.apache.bcel;

public interface ExceptionConstants
{
    public static final Class THROWABLE = (ExceptionConstants$1.class$java$lang$Throwable == null) ? (ExceptionConstants$1.class$java$lang$Throwable = ExceptionConstants$1.class$("java.lang.Throwable")) : ExceptionConstants$1.class$java$lang$Throwable;
    public static final Class RUNTIME_EXCEPTION = (ExceptionConstants$1.class$java$lang$RuntimeException == null) ? (ExceptionConstants$1.class$java$lang$RuntimeException = ExceptionConstants$1.class$("java.lang.RuntimeException")) : ExceptionConstants$1.class$java$lang$RuntimeException;
    public static final Class LINKING_EXCEPTION = (ExceptionConstants$1.class$java$lang$LinkageError == null) ? (ExceptionConstants$1.class$java$lang$LinkageError = ExceptionConstants$1.class$("java.lang.LinkageError")) : ExceptionConstants$1.class$java$lang$LinkageError;
    public static final Class CLASS_CIRCULARITY_ERROR = (ExceptionConstants$1.class$java$lang$ClassCircularityError == null) ? (ExceptionConstants$1.class$java$lang$ClassCircularityError = ExceptionConstants$1.class$("java.lang.ClassCircularityError")) : ExceptionConstants$1.class$java$lang$ClassCircularityError;
    public static final Class CLASS_FORMAT_ERROR = (ExceptionConstants$1.class$java$lang$ClassFormatError == null) ? (ExceptionConstants$1.class$java$lang$ClassFormatError = ExceptionConstants$1.class$("java.lang.ClassFormatError")) : ExceptionConstants$1.class$java$lang$ClassFormatError;
    public static final Class EXCEPTION_IN_INITIALIZER_ERROR = (ExceptionConstants$1.class$java$lang$ExceptionInInitializerError == null) ? (ExceptionConstants$1.class$java$lang$ExceptionInInitializerError = ExceptionConstants$1.class$("java.lang.ExceptionInInitializerError")) : ExceptionConstants$1.class$java$lang$ExceptionInInitializerError;
    public static final Class INCOMPATIBLE_CLASS_CHANGE_ERROR = (ExceptionConstants$1.class$java$lang$IncompatibleClassChangeError == null) ? (ExceptionConstants$1.class$java$lang$IncompatibleClassChangeError = ExceptionConstants$1.class$("java.lang.IncompatibleClassChangeError")) : ExceptionConstants$1.class$java$lang$IncompatibleClassChangeError;
    public static final Class ABSTRACT_METHOD_ERROR = (ExceptionConstants$1.class$java$lang$AbstractMethodError == null) ? (ExceptionConstants$1.class$java$lang$AbstractMethodError = ExceptionConstants$1.class$("java.lang.AbstractMethodError")) : ExceptionConstants$1.class$java$lang$AbstractMethodError;
    public static final Class ILLEGAL_ACCESS_ERROR = (ExceptionConstants$1.class$java$lang$IllegalAccessError == null) ? (ExceptionConstants$1.class$java$lang$IllegalAccessError = ExceptionConstants$1.class$("java.lang.IllegalAccessError")) : ExceptionConstants$1.class$java$lang$IllegalAccessError;
    public static final Class INSTANTIATION_ERROR = (ExceptionConstants$1.class$java$lang$InstantiationError == null) ? (ExceptionConstants$1.class$java$lang$InstantiationError = ExceptionConstants$1.class$("java.lang.InstantiationError")) : ExceptionConstants$1.class$java$lang$InstantiationError;
    public static final Class NO_SUCH_FIELD_ERROR = (ExceptionConstants$1.class$java$lang$NoSuchFieldError == null) ? (ExceptionConstants$1.class$java$lang$NoSuchFieldError = ExceptionConstants$1.class$("java.lang.NoSuchFieldError")) : ExceptionConstants$1.class$java$lang$NoSuchFieldError;
    public static final Class NO_SUCH_METHOD_ERROR = (ExceptionConstants$1.class$java$lang$NoSuchMethodError == null) ? (ExceptionConstants$1.class$java$lang$NoSuchMethodError = ExceptionConstants$1.class$("java.lang.NoSuchMethodError")) : ExceptionConstants$1.class$java$lang$NoSuchMethodError;
    public static final Class NO_CLASS_DEF_FOUND_ERROR = (ExceptionConstants$1.class$java$lang$NoClassDefFoundError == null) ? (ExceptionConstants$1.class$java$lang$NoClassDefFoundError = ExceptionConstants$1.class$("java.lang.NoClassDefFoundError")) : ExceptionConstants$1.class$java$lang$NoClassDefFoundError;
    public static final Class UNSATISFIED_LINK_ERROR = (ExceptionConstants$1.class$java$lang$UnsatisfiedLinkError == null) ? (ExceptionConstants$1.class$java$lang$UnsatisfiedLinkError = ExceptionConstants$1.class$("java.lang.UnsatisfiedLinkError")) : ExceptionConstants$1.class$java$lang$UnsatisfiedLinkError;
    public static final Class VERIFY_ERROR = (ExceptionConstants$1.class$java$lang$VerifyError == null) ? (ExceptionConstants$1.class$java$lang$VerifyError = ExceptionConstants$1.class$("java.lang.VerifyError")) : ExceptionConstants$1.class$java$lang$VerifyError;
    public static final Class NULL_POINTER_EXCEPTION = (ExceptionConstants$1.class$java$lang$NullPointerException == null) ? (ExceptionConstants$1.class$java$lang$NullPointerException = ExceptionConstants$1.class$("java.lang.NullPointerException")) : ExceptionConstants$1.class$java$lang$NullPointerException;
    public static final Class ARRAY_INDEX_OUT_OF_BOUNDS_EXCEPTION = (ExceptionConstants$1.class$java$lang$ArrayIndexOutOfBoundsException == null) ? (ExceptionConstants$1.class$java$lang$ArrayIndexOutOfBoundsException = ExceptionConstants$1.class$("java.lang.ArrayIndexOutOfBoundsException")) : ExceptionConstants$1.class$java$lang$ArrayIndexOutOfBoundsException;
    public static final Class ARITHMETIC_EXCEPTION = (ExceptionConstants$1.class$java$lang$ArithmeticException == null) ? (ExceptionConstants$1.class$java$lang$ArithmeticException = ExceptionConstants$1.class$("java.lang.ArithmeticException")) : ExceptionConstants$1.class$java$lang$ArithmeticException;
    public static final Class NEGATIVE_ARRAY_SIZE_EXCEPTION = (ExceptionConstants$1.class$java$lang$NegativeArraySizeException == null) ? (ExceptionConstants$1.class$java$lang$NegativeArraySizeException = ExceptionConstants$1.class$("java.lang.NegativeArraySizeException")) : ExceptionConstants$1.class$java$lang$NegativeArraySizeException;
    public static final Class CLASS_CAST_EXCEPTION = (ExceptionConstants$1.class$java$lang$ClassCastException == null) ? (ExceptionConstants$1.class$java$lang$ClassCastException = ExceptionConstants$1.class$("java.lang.ClassCastException")) : ExceptionConstants$1.class$java$lang$ClassCastException;
    public static final Class ILLEGAL_MONITOR_STATE = (ExceptionConstants$1.class$java$lang$IllegalMonitorStateException == null) ? (ExceptionConstants$1.class$java$lang$IllegalMonitorStateException = ExceptionConstants$1.class$("java.lang.IllegalMonitorStateException")) : ExceptionConstants$1.class$java$lang$IllegalMonitorStateException;
    public static final Class[] EXCS_CLASS_AND_INTERFACE_RESOLUTION = { ExceptionConstants.NO_CLASS_DEF_FOUND_ERROR, ExceptionConstants.CLASS_FORMAT_ERROR, ExceptionConstants.VERIFY_ERROR, ExceptionConstants.ABSTRACT_METHOD_ERROR, ExceptionConstants.EXCEPTION_IN_INITIALIZER_ERROR, ExceptionConstants.ILLEGAL_ACCESS_ERROR };
    public static final Class[] EXCS_FIELD_AND_METHOD_RESOLUTION = { ExceptionConstants.NO_SUCH_FIELD_ERROR, ExceptionConstants.ILLEGAL_ACCESS_ERROR, ExceptionConstants.NO_SUCH_METHOD_ERROR };
    public static final Class[] EXCS_INTERFACE_METHOD_RESOLUTION = new Class[0];
    public static final Class[] EXCS_STRING_RESOLUTION = new Class[0];
    public static final Class[] EXCS_ARRAY_EXCEPTION = { ExceptionConstants.NULL_POINTER_EXCEPTION, ExceptionConstants.ARRAY_INDEX_OUT_OF_BOUNDS_EXCEPTION };
}
