// 
// Decompiled by Procyon v0.5.30
// 

package org.apache.activemq.openwire.tool;

import java.util.List;
import org.codehaus.jam.JClass;
import java.util.Iterator;
import org.codehaus.jam.JProperty;
import java.io.Writer;
import java.io.PrintWriter;
import java.io.StringWriter;
import java.io.File;

public class CSharpClassesGenerator extends MultiSourceGenerator
{
    protected String targetDir;
    
    public CSharpClassesGenerator() {
        this.targetDir = "./src/main/csharp";
    }
    
    @Override
    public Object run() {
        this.filePostFix = ".cs";
        if (this.destDir == null) {
            this.destDir = new File(this.targetDir + "/ActiveMQ/Commands");
        }
        return super.run();
    }
    
    public String makeHashCodeBody() throws Exception {
        if (this.simpleName.endsWith("Id")) {
            final StringWriter buffer = new StringWriter();
            final PrintWriter out = new PrintWriter(buffer);
            out.println("            int answer = 0;");
            for (final JProperty property : this.getProperties()) {
                out.println("            answer = (answer * 37) + HashCode(" + property.getSimpleName() + ");");
            }
            out.println("            return answer;");
            return buffer.toString();
        }
        return null;
    }
    
    public String makeEqualsBody() throws Exception {
        if (this.simpleName.endsWith("Id")) {
            final StringWriter buffer = new StringWriter();
            final PrintWriter out = new PrintWriter(buffer);
            for (final JProperty property : this.getProperties()) {
                final String name = property.getSimpleName();
                out.println("            if (! Equals(this." + name + ", that." + name + ")) return false;");
            }
            out.println("            return true;");
            return buffer.toString();
        }
        return null;
    }
    
    public String makeToStringBody() throws Exception {
        final StringWriter buffer = new StringWriter();
        final PrintWriter out = new PrintWriter(buffer);
        out.println("            return GetType().Name + \"[\"");
        for (final JProperty property : this.getProperties()) {
            final String name = property.getSimpleName();
            out.println("                + \" " + name + "=\" + " + name);
        }
        out.println("                + \" ]\";");
        return buffer.toString();
    }
    
    private void generateLicence(final PrintWriter out) {
        out.println("/*");
        out.println(" * Licensed to the Apache Software Foundation (ASF) under one or more");
        out.println(" * contributor license agreements.  See the NOTICE file distributed with");
        out.println(" * this work for additional information regarding copyright ownership.");
        out.println(" * The ASF licenses this file to You under the Apache License, Version 2.0");
        out.println(" * (the \"License\"); you may not use this file except in compliance with");
        out.println(" * the License.  You may obtain a copy of the License at");
        out.println(" *");
        out.println(" * http://www.apache.org/licenses/LICENSE-2.0");
        out.println(" *");
        out.println(" * Unless required by applicable law or agreed to in writing, software");
        out.println(" * distributed under the License is distributed on an \"AS IS\" BASIS,");
        out.println(" * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.");
        out.println(" * See the License for the specific language governing permissions and");
        out.println(" * limitations under the License.");
        out.println(" */");
    }
    
    @Override
    protected void generateFile(final PrintWriter out) throws Exception {
        this.generateLicence(out);
        out.println("//");
        out.println("//  NOTE!: This file is autogenerated - do not modify!");
        out.println("//         if you need to make a change, please see the Groovy scripts in the");
        out.println("//         activemq-core module");
        out.println("//");
        out.println("");
        out.println("using System;");
        out.println("using System.Collections;");
        out.println("");
        out.println("using ActiveMQ.OpenWire;");
        out.println("using ActiveMQ.Commands;");
        out.println("");
        out.println("namespace ActiveMQ.Commands");
        out.println("{");
        out.println("    /// <summary>");
        out.println("    ///  The ActiveMQ " + this.jclass.getSimpleName() + " Command");
        out.println("    /// </summary>");
        out.print("    public class " + this.jclass.getSimpleName() + " : " + this.baseClass);
        for (int i = 0; i < this.jclass.getInterfaces().length; ++i) {
            final JClass intf = this.jclass.getInterfaces()[i];
            out.print(", " + intf.getSimpleName());
        }
        out.println("");
        out.println("    {");
        out.println("        public const byte ID_" + this.jclass.getSimpleName() + " = " + this.getOpenWireOpCode(this.jclass) + ";");
        out.println("                ");
        final List properties = this.getProperties();
        for (final JProperty property : properties) {
            final String type = this.toCSharpType(property.getType());
            final Object name = this.decapitalize(property.getSimpleName());
            out.println("        " + type + " " + name + ";");
        }
        String text = this.makeHashCodeBody();
        if (text != null) {
            out.println("");
            out.println("        public override int GetHashCode() {");
            out.println("" + text + "");
            out.println("        }");
        }
        text = this.makeEqualsBody();
        if (text != null) {
            out.println("");
            out.println("        public override bool Equals(object that) {");
            out.println("            if (that is " + this.className + ") {");
            out.println("                return Equals((" + this.className + ") that);");
            out.println("            }");
            out.println("            return false;");
            out.println("        }");
            out.println("");
            out.println("        public virtual bool Equals(" + this.className + " that) {");
            out.println("" + text + "");
            out.println("        }");
        }
        text = this.makeToStringBody();
        if (text != null) {
            out.println("");
            out.println("        public override string ToString() {");
            out.println("" + text + "");
            out.println("        }");
        }
        out.println("");
        out.println("        public override byte GetDataStructureType() {");
        out.println("            return ID_" + this.jclass.getSimpleName() + ";");
        out.println("        }");
        out.println("");
        out.println("");
        out.println("        // Properties");
        for (final JProperty property2 : properties) {
            final String type = this.toCSharpType(property2.getType());
            final Object name = this.decapitalize(property2.getSimpleName());
            final String propertyName = property2.getSimpleName();
            out.println("");
            out.println("        public " + type + " " + propertyName + "");
            out.println("        {");
            out.println("            get { return " + name + "; }");
            out.println("            set { this." + name + " = value; }            ");
            out.println("        }");
        }
        out.println("");
        out.println("    }");
        out.println("}");
    }
    
    public String getTargetDir() {
        return this.targetDir;
    }
    
    public void setTargetDir(final String targetDir) {
        this.targetDir = targetDir;
    }
}
