// 
// Decompiled by Procyon v0.5.30
// 

package com.neurotec.biometrics.standards;

public class CbeffBdbFormatIdentifiers
{
    public static final int INCITS_TC_M1_BIOMETRICS_FINGER_MINUTIAE_N = 513;
    public static final int INCITS_TC_M1_BIOMETRICS_FINGER_MINUTIAE_X = 514;
    public static final int INCITS_TC_M1_BIOMETRICS_FINGER_MINUTIAE_U = 515;
    public static final int INCITS_TC_M1_BIOMETRICS_FINGER_PATTERN_N = 769;
    public static final int INCITS_TC_M1_BIOMETRICS_FINGER_IMAGE = 1025;
    public static final int INCITS_TC_M1_BIOMETRICS_FACE_IMAGE = 1281;
    public static final int INCITS_TC_M1_BIOMETRICS_IRIS_RECTILINEAR = 1537;
    public static final int INCITS_TC_M1_BIOMETRICS_IRIS_POLAR = 1538;
    public static final int INCITS_TC_M1_BIOMETRICS_SIGNATURE_SIGN_RAW_DATA_N = 1793;
    public static final int INCITS_TC_M1_BIOMETRICS_SIGNATURE_SIGN_RAW_DATA_X = 1794;
    public static final int INCITS_TC_M1_BIOMETRICS_SIGNATURE_SIGN_COMMON_FEATURE_DATA_N = 1795;
    public static final int INCITS_TC_M1_BIOMETRICS_SIGNATURE_SIGN_COMMON_FEATURE_DATA_X = 1796;
    public static final int INCITS_TC_M1_BIOMETRICS_SIGNATURE_SIGN_RAW_AND_COMMON_FEATURE_DATA_N = 1797;
    public static final int INCITS_TC_M1_BIOMETRICS_SIGNATURE_SIGN_RAW_AND_COMMON_FEATURE_DATA_X = 1798;
    public static final int INCITS_TC_M1_BIOMETRICS_HAND_GEOMETRY_N = 2049;
    public static final int INCITS_TC_M1_BIOMETRICS_HAND_GEOMETRY_X = 2050;
    public static final int INCITS_TC_M1_BIOMETRICS_BIOMETRIC_FUSION_DATA = 2305;
    public static final int INCITS_TC_M1_BIOMETRICS_WSQ_IMAGE = 32769;
    public static final int INCITS_TC_M1_BIOMETRICS_BMP_IMAGE = 32770;
    public static final int INCITS_TC_M1_BIOMETRICS_JPEG_IMAGE = 32771;
    public static final int INCITS_TC_M1_BIOMETRICS_JPEG2000_IMAGE = 32772;
    public static final int INCITS_TC_M1_BIOMETRICS_TIFF_IMAGE = 32773;
    public static final int INCITS_TC_M1_BIOMETRICS_GIF89A_IMAGE = 32774;
    public static final int INCITS_TC_M1_BIOMETRICS_PNG_IMAGE = 32775;
    public static final int INCITS_TC_M1_BIOMETRICS_WAV_AUDIO = 32776;
    public static final int INCITS_TC_M1_BIOMETRICS_MPEG_MEDIA = 32777;
    public static final int INCITS_TC_M1_BIOMETRICS_MPEG1_PART_3_MEDIA = 32778;
    public static final int INCITS_TC_M1_BIOMETRICS_AVI_MEDIA = 32779;
    public static final int INCITS_TC_M1_BIOMETRICS_VRML_3D_OBJECT_DATA = 32780;
    public static final int INCITS_TC_M1_BIOMETRICS_NIST_ITL_1_2000_TYPE_4_RECORD = 32781;
    public static final int INCITS_TC_M1_BIOMETRICS_NIST_ITL_1_2000_TYPE_10_RECORD = 32782;
    public static final int INCITS_TC_M1_BIOMETRICS_NIST_ITL_1_2000_TYPE_13_RECORD = 32783;
    public static final int INCITS_TC_M1_BIOMETRICS_NIST_ITL_1_2000_TYPE_14_RECORD = 32784;
    public static final int INCITS_TC_M1_BIOMETRICS_NIST_ITL_1_2000_TYPE_15_RECORD = 32785;
    public static final int INCITS_TC_M1_BIOMETRICS_NIST_ITL_1_2000_TYPE_16_RECORD = 32786;
    public static final int INCITS_TC_M1_BIOMETRICS_NIST_ITL_1_200X_RECORD_COLLECTION_FOR_TENPRINT_CAPTURE = 32787;
    public static final int INCITS_TC_M1_BIOMETRICS_GENERIC_FBI_EFTS_RECORD = 32788;
    public static final int INCITS_TC_M1_BIOMETRICS_NIEM = 32789;
    public static final int INCITS_TC_M1_BIOMETRICS_NIST_ITL1_2007_TYPE_10_RECORD = 32790;
    public static final int INCITS_TC_M1_BIOMETRICS_NIST_ITL1_2007_TYPE_14_RECORD = 32791;
    public static final int INCITS_TC_M1_BIOMETRICS_NIST_ITL1_2007_TYPE_17_RECORD = 32792;
    public static final int INCITS_TC_M1_BIOMETRICS_EBTS = 32793;
    public static final int NEUROTECHNOLOGIJA_NLRECORD_3 = 770;
    public static final int NEUROTECHNOLOGIJA_NTEMPLATE = 0;
    public static final int ID3_SEMICONDUCTORS_COMPACT_CARD_EXTENSION = 1;
    public static final int FEDERAL_OFFICE_FOR_INFORMATION_SECURITY_TR_BIOMETRICS_XML_FACE_1_0 = 1;
    public static final int FEDERAL_OFFICE_FOR_INFORMATION_SECURITY_TR_BIOMETRICS_XML_FINGER_1_0 = 2;
    public static final int BIOLOGICA_SISTEMAS_ISO_19794_2_BIOUNISTATION = 2;
    public static final int BIOLOGICA_SISTEMAS_ISO_19794_4_BIOUNISTATION = 4;
    public static final int BIOLOGICA_SISTEMAS_ISO_19794_5_BIOUNISTATION = 5;
    public static final int ISO_IEC_JTC_1_SC_37_BIOMETRICS_FINGER_MINUTIAE_RECORD_N = 1;
    public static final int ISO_IEC_JTC_1_SC_37_BIOMETRICS_FINGER_MINUTIAE_RECORD_X = 2;
    public static final int ISO_IEC_JTC_1_SC_37_BIOMETRICS_FINGER_MINUTIAE_CARD_NORMAL_V = 3;
    public static final int ISO_IEC_JTC_1_SC_37_BIOMETRICS_FINGER_MINUTIAE_CARD_NORMAL_N = 4;
    public static final int ISO_IEC_JTC_1_SC_37_BIOMETRICS_FINGER_MINUTIAE_CARD_COMPACT_V = 5;
    public static final int ISO_IEC_JTC_1_SC_37_BIOMETRICS_FINGER_MINUTIAE_CARD_COMPACT_N = 6;
    public static final int ISO_IEC_JTC_1_SC_37_BIOMETRICS_FINGER_IMAGE = 7;
    public static final int ISO_IEC_JTC_1_SC_37_BIOMETRICS_FACE_IMAGE = 8;
    public static final int ISO_IEC_JTC_1_SC_37_BIOMETRICS_IRIS_IMAGE_RECTILINEAR = 9;
    public static final int ISO_IEC_JTC_1_SC_37_BIOMETRICS_FINGER_PATTERN_SPECTRAL_QUANTIZED_CO_SINUSOIDAL_TRIPLET = 10;
    public static final int ISO_IEC_JTC_1_SC_37_BIOMETRICS_IRIS_IMAGE_POLAR = 11;
    public static final int ISO_IEC_JTC_1_SC_37_BIOMETRICS_FINGER_PATTERN_SPECTRAL_DISCRETE_FOURIER_TRANSFORM = 12;
    public static final int ISO_IEC_JTC_1_SC_37_BIOMETRICS_FINGER_PATTERN_SPECTRAL_GABOR_FILTER = 13;
    public static final int ISO_IEC_JTC_1_SC_37_BIOMETRICS_SIGNATURE_SIGN_TIME_SERIES_FULL = 14;
    public static final int ISO_IEC_JTC_1_SC_37_BIOMETRICS_SIGNATURE_SIGN_TIME_SERIES_COMPACT = 15;
    public static final int ISO_IEC_JTC_1_SC_37_BIOMETRICS_FINGER_PATTERN_SKELETAL_DATA_RECORD = 17;
    public static final int ISO_IEC_JTC_1_SC_37_BIOMETRICS_FINGER_PATTERN_SKELETAL_DATA_CARD_NORMAL = 18;
    public static final int ISO_IEC_JTC_1_SC_37_BIOMETRICS_FINGER_PATTERN_SKELETAL_DATA_CARD_COMPACT = 19;
    public static final int ISO_IEC_JTC_1_SC_37_BIOMETRICS_VASCULAR_IMAGE_DATA = 20;
    public static final int ISO_IEC_JTC_1_SC_37_BIOMETRICS_HAND_GEOMETRY_SILHOUETTE = 24;
    public static final int ISO_IEC_JTC_1_SC_37_BIOMETRICS_FINGER_MINUTIAE_CARD_COMPACT_V_H = 25;
    public static final int ISO_IEC_JTC_1_SC_37_BIOMETRICS_FINGER_MINUTIAE_CARD_COMPACT_R_H = 26;
    public static final int ISO_IEC_JTC_1_SC_37_BIOMETRICS_FINGER_MINUTIAE_CARD_NORMAL_V_NH = 27;
    public static final int ISO_IEC_JTC_1_SC_27_IT_SECURITY_TECHNIQUES_BIOMETRIC_REFERENCE_TEMPLATE_CERTIFICATE = 1;
    public static final int ISO_IEC_JTC_1_SC_37_BIOMETRICS_FINGER_MINUTIAE_CARD_NORMAL_R_NH = 28;
}
