// 
// Decompiled by Procyon v0.5.30
// 

package org.jbox2d.testbed.tests;

import org.jbox2d.dynamics.joints.JointDef;
import org.jbox2d.collision.ShapeDef;
import org.jbox2d.dynamics.BodyDef;
import org.jbox2d.common.Vec2;
import org.jbox2d.dynamics.joints.RevoluteJoint;
import org.jbox2d.dynamics.Body;
import org.jbox2d.dynamics.World;

public class Biped
{
    private World m_world;
    private Body LFoot;
    private Body RFoot;
    private Body LCalf;
    private Body RCalf;
    private Body LThigh;
    private Body RThigh;
    private Body Pelvis;
    private Body Stomach;
    private Body Chest;
    private Body Neck;
    private Body Head;
    private Body LUpperArm;
    private Body RUpperArm;
    private Body LForearm;
    private Body RForearm;
    private Body LHand;
    private Body RHand;
    private RevoluteJoint LAnkle;
    private RevoluteJoint RAnkle;
    private RevoluteJoint LKnee;
    private RevoluteJoint RKnee;
    private RevoluteJoint LHip;
    private RevoluteJoint RHip;
    private RevoluteJoint LowerAbs;
    private RevoluteJoint UpperAbs;
    private RevoluteJoint LowerNeck;
    private RevoluteJoint UpperNeck;
    private RevoluteJoint LShoulder;
    private RevoluteJoint RShoulder;
    private RevoluteJoint LElbow;
    private RevoluteJoint RElbow;
    private RevoluteJoint LWrist;
    private RevoluteJoint RWrist;
    
    public Biped(final World w, final Vec2 position) {
        this.m_world = w;
        final BipedDef def = new BipedDef();
        BodyDef bd = new BodyDef();
        bd = def.LFootDef;
        bd.position.addLocal(position);
        (this.LFoot = w.createDynamicBody(bd)).createShape(def.LFootPoly);
        this.LFoot.setMassFromShapes();
        bd = def.RFootDef;
        bd.position.addLocal(position);
        (this.RFoot = w.createDynamicBody(bd)).createShape(def.RFootPoly);
        this.RFoot.setMassFromShapes();
        bd = def.LCalfDef;
        bd.position.addLocal(position);
        (this.LCalf = w.createDynamicBody(bd)).createShape(def.LCalfPoly);
        this.LCalf.setMassFromShapes();
        bd = def.RCalfDef;
        bd.position.addLocal(position);
        (this.RCalf = w.createDynamicBody(bd)).createShape(def.RCalfPoly);
        this.RCalf.setMassFromShapes();
        bd = def.LThighDef;
        bd.position.addLocal(position);
        (this.LThigh = w.createDynamicBody(bd)).createShape(def.LThighPoly);
        this.LThigh.setMassFromShapes();
        bd = def.RThighDef;
        bd.position.addLocal(position);
        (this.RThigh = w.createDynamicBody(bd)).createShape(def.RThighPoly);
        this.RThigh.setMassFromShapes();
        bd = def.PelvisDef;
        bd.position.addLocal(position);
        (this.Pelvis = w.createDynamicBody(bd)).createShape(def.PelvisPoly);
        this.Pelvis.setMassFromShapes();
        bd = def.StomachDef;
        bd.position.addLocal(position);
        (this.Stomach = w.createDynamicBody(bd)).createShape(def.StomachPoly);
        this.Stomach.setMassFromShapes();
        bd = def.ChestDef;
        bd.position.addLocal(position);
        (this.Chest = w.createDynamicBody(bd)).createShape(def.ChestPoly);
        this.Chest.setMassFromShapes();
        bd = def.NeckDef;
        bd.position.addLocal(position);
        (this.Neck = w.createDynamicBody(bd)).createShape(def.NeckPoly);
        this.Neck.setMassFromShapes();
        bd = def.HeadDef;
        bd.position.addLocal(position);
        (this.Head = w.createDynamicBody(bd)).createShape(def.HeadCirc);
        this.Head.setMassFromShapes();
        bd = def.LUpperArmDef;
        bd.position.addLocal(position);
        (this.LUpperArm = w.createDynamicBody(bd)).createShape(def.LUpperArmPoly);
        this.LUpperArm.setMassFromShapes();
        bd = def.RUpperArmDef;
        bd.position.addLocal(position);
        (this.RUpperArm = w.createDynamicBody(bd)).createShape(def.RUpperArmPoly);
        this.RUpperArm.setMassFromShapes();
        bd = def.LForearmDef;
        bd.position.addLocal(position);
        (this.LForearm = w.createDynamicBody(bd)).createShape(def.LForearmPoly);
        this.LForearm.setMassFromShapes();
        bd = def.RForearmDef;
        bd.position.addLocal(position);
        (this.RForearm = w.createDynamicBody(bd)).createShape(def.RForearmPoly);
        this.RForearm.setMassFromShapes();
        bd = def.LHandDef;
        bd.position.addLocal(position);
        (this.LHand = w.createDynamicBody(bd)).createShape(def.LHandPoly);
        this.LHand.setMassFromShapes();
        bd = def.RHandDef;
        bd.position.addLocal(position);
        (this.RHand = w.createDynamicBody(bd)).createShape(def.RHandPoly);
        this.RHand.setMassFromShapes();
        def.LAnkleDef.body1 = this.LFoot;
        def.LAnkleDef.body2 = this.LCalf;
        def.RAnkleDef.body1 = this.RFoot;
        def.RAnkleDef.body2 = this.RCalf;
        def.LKneeDef.body1 = this.LCalf;
        def.LKneeDef.body2 = this.LThigh;
        def.RKneeDef.body1 = this.RCalf;
        def.RKneeDef.body2 = this.RThigh;
        def.LHipDef.body1 = this.LThigh;
        def.LHipDef.body2 = this.Pelvis;
        def.RHipDef.body1 = this.RThigh;
        def.RHipDef.body2 = this.Pelvis;
        def.LowerAbsDef.body1 = this.Pelvis;
        def.LowerAbsDef.body2 = this.Stomach;
        def.UpperAbsDef.body1 = this.Stomach;
        def.UpperAbsDef.body2 = this.Chest;
        def.LowerNeckDef.body1 = this.Chest;
        def.LowerNeckDef.body2 = this.Neck;
        def.UpperNeckDef.body1 = this.Chest;
        def.UpperNeckDef.body2 = this.Head;
        def.LShoulderDef.body1 = this.Chest;
        def.LShoulderDef.body2 = this.LUpperArm;
        def.RShoulderDef.body1 = this.Chest;
        def.RShoulderDef.body2 = this.RUpperArm;
        def.LElbowDef.body1 = this.LForearm;
        def.LElbowDef.body2 = this.LUpperArm;
        def.RElbowDef.body1 = this.RForearm;
        def.RElbowDef.body2 = this.RUpperArm;
        def.LWristDef.body1 = this.LHand;
        def.LWristDef.body2 = this.LForearm;
        def.RWristDef.body1 = this.RHand;
        def.RWristDef.body2 = this.RForearm;
        this.LAnkle = (RevoluteJoint)w.createJoint(def.LAnkleDef);
        this.RAnkle = (RevoluteJoint)w.createJoint(def.RAnkleDef);
        this.LKnee = (RevoluteJoint)w.createJoint(def.LKneeDef);
        this.RKnee = (RevoluteJoint)w.createJoint(def.RKneeDef);
        this.LHip = (RevoluteJoint)w.createJoint(def.LHipDef);
        this.RHip = (RevoluteJoint)w.createJoint(def.RHipDef);
        this.LowerAbs = (RevoluteJoint)w.createJoint(def.LowerAbsDef);
        this.UpperAbs = (RevoluteJoint)w.createJoint(def.UpperAbsDef);
        this.LowerNeck = (RevoluteJoint)w.createJoint(def.LowerNeckDef);
        this.UpperNeck = (RevoluteJoint)w.createJoint(def.UpperNeckDef);
        this.LShoulder = (RevoluteJoint)w.createJoint(def.LShoulderDef);
        this.RShoulder = (RevoluteJoint)w.createJoint(def.RShoulderDef);
        this.LElbow = (RevoluteJoint)w.createJoint(def.LElbowDef);
        this.RElbow = (RevoluteJoint)w.createJoint(def.RElbowDef);
        this.LWrist = (RevoluteJoint)w.createJoint(def.LWristDef);
        this.RWrist = (RevoluteJoint)w.createJoint(def.RWristDef);
    }
}
