// 
// Decompiled by Procyon v0.5.30
// 

package com.masystem.beergame.network.protocol;

public enum Status
{
    NONE, 
    OK, 
    ERROR_UNKNOWN, 
    ERROR_CONNECTION_FAILED, 
    ERROR_CONNECTION_ABORTED, 
    ERROR_PLAYER_NOT_CONNECTED, 
    ERROR_PLAYER_NOT_LOGGED_IN, 
    ERROR_PLAYER_ALREADY_LOGGED_IN, 
    ERROR_PLAYER_INVALID_NAME, 
    ERROR_PLAYER_INVALID_TYPE, 
    ERROR_PLAYER_ALREADY_EXISTS, 
    ERROR_PLAYER_NOT_IN_GAME, 
    ERROR_GAME_INVALID_NAME, 
    ERROR_GAME_ALREADY_EXISTS, 
    ERROR_GAME_DOES_NOT_EXIST, 
    ERROR_GAME_MUST_BE_SELECTED, 
    ERROR_GAME_ALREADY_HAS_PLAYER_TYPE, 
    ERROR_NOT_AUTHORIZED, 
    ERROR_COMMAND_UNKNOWN, 
    ERROR_COMMAND_ILLEGAL;
}
