// 
// Decompiled by Procyon v0.5.30
// 

package a.a.a;

public enum i
{
    d("partnerId", 0), 
    e("partnerSite", 1), 
    f("partnerKey", 2), 
    g("partnerExpires", 3), 
    h("autoStart", 4), 
    i("captureId", 5), 
    j("captureOption", 6), 
    k("continueOk", 7), 
    l("captureSize", 8), 
    m("captureTitle", 9), 
    n("captureType", 10), 
    o("doneHotKey", 11), 
    p("frameRate", 12), 
    q("maxCaptureSec", 13), 
    r("maxCaptureSize", 14), 
    s("micName", 15), 
    t("trackMouse", 16), 
    u("showClicks", 17), 
    v("showHalo", 18), 
    w("writeMouseOnFrame", 19), 
    x("toggleRecordHotKey", 20), 
    y("minResizeSize", 21), 
    z("countDownSec", 22), 
    A("smoothMouse", 23), 
    B("micAmplify", 24), 
    C("maxAudioSampleRate", 25), 
    D("loadLastCapture", 26), 
    E("checkDefault", 27), 
    F("demoId", 28), 
    G("filePath", 29), 
    H("uploadPostUrl", 30), 
    I("uploadPostImgUrl", 31), 
    J("uploadPostImgUrlResize", 32), 
    K("uploadPostFileType", 33), 
    L("uploadPostDeleteAfter", 34), 
    M("uploadPostEncoderUrl", 35), 
    N("uploadPostEncoderExe", 36), 
    O("uploadPostHeader", 37), 
    P("uploadPostMaxWidth", 38), 
    Q("uploadPostMethod", 39), 
    R("uploadPostUseProxyFromOS", 40), 
    S("uploadPostRequestUrl", 41), 
    T("uploadPostLaunchUrlAfter", 42), 
    U("uploadPostLaunchUrlBefore", 43), 
    V("exportFileEncoderUrl", 44), 
    W("exportFileEncoderExe", 45), 
    X("exportFilePath", 46), 
    Y("exportFileMaxWidth", 47), 
    Z("exportFileType", 48), 
    a("doSetup", 49), 
    aa("doFindMics", 50), 
    ab("doCheckExists", 51), 
    ac("doGetInfo", 52), 
    ad("doSetInfo", 53), 
    ae("doCheckMic", 54), 
    af("doCapture", 55), 
    ag("doDelete", 56), 
    ah("doDetail", 57), 
    ai("doList", 58), 
    aj("doDemoList", 59), 
    ak("doListMods", 60), 
    al("doPlayback", 61), 
    am("doGetPath", 62), 
    an("doExport", 63), 
    ao("doUpload", 64), 
    ap("doUploadLog", 65), 
    b("doIfVerifyFailed", 66), 
    c("doIfCertDenied", 67), 
    aq("doEditor", 68), 
    ar("doDemoEditor", 69), 
    as("doStartImgServer", 70), 
    at("doSOMImport", 71), 
    au("doSOMExport", 72), 
    av("mp4FastStartUrl", 73), 
    aw("mp4FastStartExe", 74), 
    ax("up", 75), 
    ay("wm", 76);
    
    private i(final String s, final int n) {
    }
    
    static {
        az = new i[] { i.d, i.e, i.f, i.g, i.h, i.i, i.j, i.k, i.l, i.m, i.n, i.o, i.p, i.q, i.r, i.s, i.t, i.u, i.v, i.w, i.x, i.y, i.z, i.A, i.B, i.C, i.D, i.E, i.F, i.G, i.H, i.I, i.J, i.K, i.L, i.M, i.N, i.O, i.P, i.Q, i.R, i.S, i.T, i.U, i.V, i.W, i.X, i.Y, i.Z, i.a, i.aa, i.ab, i.ac, i.ad, i.ae, i.af, i.ag, i.ah, i.ai, i.aj, i.ak, i.al, i.am, i.an, i.ao, i.ap, i.b, i.c, i.aq, i.ar, i.as, i.at, i.au, i.av, i.aw, i.ax, i.ay };
    }
}
