import java.awt.Event;
import java.awt.LayoutManager;
import java.awt.BorderLayout;
import java.awt.GridBagConstraints;
import java.awt.Dimension;
import java.awt.Insets;
import java.awt.GridBagLayout;
import java.awt.Component;
import java.awt.Panel;
import java.awt.Frame;

// 
// Decompiled by Procyon v0.5.30
// 

class PGC_DetailsFrame extends Frame
{
    private PGC owner;
    private Panel pnl_root;
    public Panel pnl_coordinates;
    public Panel pnl_expressions;
    public Panel pnl_parametric;
    public Panel pnl_error_message;
    public PGC_LabelFixed lbl_a;
    public PGC_LabelFixed lbl_a_x;
    public PGC_LabelFixed lbl_a_y;
    public PGC_LabelFixed lbl_b;
    public PGC_LabelFixed lbl_b_x;
    public PGC_LabelFixed lbl_b_y;
    public PGC_LabelFixed lbl_c;
    public PGC_LabelFixed lbl_c_x;
    public PGC_LabelFixed lbl_c_y;
    public PGC_LabelFixed lbl_d;
    public PGC_LabelFixed lbl_d_x;
    public PGC_LabelFixed lbl_d_y;
    public PGC_LabelFixed lbl_f;
    public PGC_LabelFixed lbl_f_x;
    public PGC_LabelFixed lbl_f_y;
    public PGC_LabelFixed lbl_g;
    public PGC_LabelFixed lbl_g_x;
    public PGC_LabelFixed lbl_g_y;
    public PGC_LabelFixed lbl_h;
    public PGC_LabelFixed lbl_h_x;
    public PGC_LabelFixed lbl_h_y;
    public PGC_LabelFixed lbl_h_def;
    public PGC_LabelFixed lbl_h_expr;
    public PGC_LabelFixed lbl_k;
    public PGC_LabelFixed lbl_k_x;
    public PGC_LabelFixed lbl_k_y;
    public PGC_LabelFixed lbl_k_def;
    public PGC_LabelFixed lbl_k_expr;
    public PGC_LabelFixed lbl_m;
    public PGC_LabelFixed lbl_m_x;
    public PGC_LabelFixed lbl_m_y;
    public PGC_LabelFixed lbl_m_def;
    public PGC_LabelFixed lbl_m_expr;
    public PGC_LabelFixed lbl_n;
    public PGC_LabelFixed lbl_n_x;
    public PGC_LabelFixed lbl_n_y;
    public PGC_LabelFixed lbl_n_def;
    public PGC_LabelFixed lbl_n_expr;
    public PGC_LabelFixed lbl_t_min;
    public PGC_LabelFixed lbl_t_max;
    public PGC_LabelFixed lbl_t_rep;
    public PGC_LabelFixed lbl_error_message;
    public PGC_TextFieldFixed txt_a_x;
    public PGC_TextFieldFixed txt_a_y;
    public PGC_TextFieldFixed txt_b_x;
    public PGC_TextFieldFixed txt_b_y;
    public PGC_TextFieldFixed txt_c_x;
    public PGC_TextFieldFixed txt_c_y;
    public PGC_TextFieldFixed txt_d_x;
    public PGC_TextFieldFixed txt_d_y;
    public PGC_TextFieldFixed txt_f_x;
    public PGC_TextFieldFixed txt_f_y;
    public PGC_TextFieldFixed txt_g_x;
    public PGC_TextFieldFixed txt_g_y;
    public PGC_TextFieldFixed txt_h_x;
    public PGC_TextFieldFixed txt_h_y;
    public PGC_TextFieldFixed txt_k_x;
    public PGC_TextFieldFixed txt_k_y;
    public PGC_TextFieldFixed txt_m_x;
    public PGC_TextFieldFixed txt_m_y;
    public PGC_TextFieldFixed txt_n_x;
    public PGC_TextFieldFixed txt_n_y;
    public PGC_TextFieldFixed txt_h_expr;
    public PGC_TextFieldFixed txt_k_expr;
    public PGC_TextFieldFixed txt_m_expr;
    public PGC_TextFieldFixed txt_n_expr;
    public PGC_TextFieldFixed txt_t_min;
    public PGC_TextFieldFixed txt_t_max;
    public PGC_TextFieldFixed txt_t_rep;
    
    public PGC_DetailsFrame(final PGC owner, final String s) {
        super(s);
        this.owner = owner;
    }
    
    private void LayoutWindow() {
        this.pnl_root = PGC.StdPanel();
        final Panel pnl_root = this.pnl_root;
        final Panel stdPanel = PGC.StdPanel();
        this.pnl_coordinates = stdPanel;
        final Panel panel = stdPanel;
        pnl_root.add(stdPanel);
        ((GridBagLayout)this.pnl_root.getLayout()).setConstraints(panel, PGC.StdConstraintsNewLine(new Insets(5, 5, 5, 5)));
        final Panel stdPanel2;
        this.pnl_coordinates.add(stdPanel2 = PGC.StdPanel());
        ((GridBagLayout)this.pnl_coordinates.getLayout()).setConstraints(stdPanel2, PGC.StdConstraintsNewLine(new Insets(0, 0, 5, 0)));
        final PGC_LabelFixed pgc_LabelFixed;
        stdPanel2.add(pgc_LabelFixed = new PGC_LabelFixed("Point coordinates", PGC.component_full_text_size));
        ((GridBagLayout)stdPanel2.getLayout()).setConstraints(pgc_LabelFixed, PGC.StdConstraints());
        final Panel stdPanel3;
        this.pnl_coordinates.add(stdPanel3 = PGC.StdPanel());
        ((GridBagLayout)this.pnl_coordinates.getLayout()).setConstraints(stdPanel3, PGC.StdConstraintsNewLine());
        final Panel pnl_coordinates = this.pnl_coordinates;
        final PGC_LabelFixed lbl_a = new PGC_LabelFixed("a", new Dimension(20, -1));
        this.lbl_a = lbl_a;
        final PGC_LabelFixed pgc_LabelFixed2 = lbl_a;
        pnl_coordinates.add(lbl_a);
        ((GridBagLayout)this.pnl_coordinates.getLayout()).setConstraints(pgc_LabelFixed2, PGC.StdConstraints());
        this.pnl_coordinates.add(this.lbl_a_x = new PGC_LabelFixed(" x= ", new Dimension(22, -1)));
        this.pnl_coordinates.add(this.txt_a_x = new PGC_TextFieldFixed(this.owner, PGC.component_number_text_size));
        this.pnl_coordinates.add(this.lbl_a_y = new PGC_LabelFixed(" y= ", new Dimension(22, -1)));
        this.pnl_coordinates.add(this.txt_a_y = new PGC_TextFieldFixed(this.owner, PGC.component_number_text_size));
        final Panel stdPanel4;
        this.pnl_coordinates.add(stdPanel4 = PGC.StdPanel());
        ((GridBagLayout)this.pnl_coordinates.getLayout()).setConstraints(stdPanel4, PGC.StdConstraintsNewLine());
        final Panel pnl_coordinates2 = this.pnl_coordinates;
        final PGC_LabelFixed lbl_b = new PGC_LabelFixed("b", new Dimension(20, -1));
        this.lbl_b = lbl_b;
        final PGC_LabelFixed pgc_LabelFixed3 = lbl_b;
        pnl_coordinates2.add(lbl_b);
        ((GridBagLayout)this.pnl_coordinates.getLayout()).setConstraints(pgc_LabelFixed3, PGC.StdConstraints());
        this.pnl_coordinates.add(this.lbl_b_x = new PGC_LabelFixed(" x= ", new Dimension(22, -1)));
        this.pnl_coordinates.add(this.txt_b_x = new PGC_TextFieldFixed(this.owner, PGC.component_number_text_size));
        this.pnl_coordinates.add(this.lbl_b_y = new PGC_LabelFixed(" y= ", new Dimension(22, -1)));
        this.pnl_coordinates.add(this.txt_b_y = new PGC_TextFieldFixed(this.owner, PGC.component_number_text_size));
        final Panel stdPanel5;
        this.pnl_coordinates.add(stdPanel5 = PGC.StdPanel());
        ((GridBagLayout)this.pnl_coordinates.getLayout()).setConstraints(stdPanel5, PGC.StdConstraintsNewLine());
        final Panel pnl_coordinates3 = this.pnl_coordinates;
        final PGC_LabelFixed lbl_c = new PGC_LabelFixed("c", new Dimension(20, -1));
        this.lbl_c = lbl_c;
        final PGC_LabelFixed pgc_LabelFixed4 = lbl_c;
        pnl_coordinates3.add(lbl_c);
        ((GridBagLayout)this.pnl_coordinates.getLayout()).setConstraints(pgc_LabelFixed4, PGC.StdConstraints());
        this.pnl_coordinates.add(this.lbl_c_x = new PGC_LabelFixed(" x= ", new Dimension(22, -1)));
        this.pnl_coordinates.add(this.txt_c_x = new PGC_TextFieldFixed(this.owner, PGC.component_number_text_size));
        this.pnl_coordinates.add(this.lbl_c_y = new PGC_LabelFixed(" y= ", new Dimension(22, -1)));
        this.pnl_coordinates.add(this.txt_c_y = new PGC_TextFieldFixed(this.owner, PGC.component_number_text_size));
        final Panel stdPanel6;
        this.pnl_coordinates.add(stdPanel6 = PGC.StdPanel());
        ((GridBagLayout)this.pnl_coordinates.getLayout()).setConstraints(stdPanel6, PGC.StdConstraintsNewLine());
        final Panel pnl_coordinates4 = this.pnl_coordinates;
        final PGC_LabelFixed lbl_d = new PGC_LabelFixed("d", new Dimension(20, -1));
        this.lbl_d = lbl_d;
        final PGC_LabelFixed pgc_LabelFixed5 = lbl_d;
        pnl_coordinates4.add(lbl_d);
        ((GridBagLayout)this.pnl_coordinates.getLayout()).setConstraints(pgc_LabelFixed5, PGC.StdConstraints());
        this.pnl_coordinates.add(this.lbl_d_x = new PGC_LabelFixed(" x= ", new Dimension(22, -1)));
        this.pnl_coordinates.add(this.txt_d_x = new PGC_TextFieldFixed(this.owner, PGC.component_number_text_size));
        this.pnl_coordinates.add(this.lbl_d_y = new PGC_LabelFixed(" y= ", new Dimension(22, -1)));
        this.pnl_coordinates.add(this.txt_d_y = new PGC_TextFieldFixed(this.owner, PGC.component_number_text_size));
        final Panel stdPanel7;
        this.pnl_coordinates.add(stdPanel7 = PGC.StdPanel());
        ((GridBagLayout)this.pnl_coordinates.getLayout()).setConstraints(stdPanel7, PGC.StdConstraintsNewLine());
        final Panel pnl_coordinates5 = this.pnl_coordinates;
        final PGC_LabelFixed lbl_f = new PGC_LabelFixed("f", new Dimension(20, -1));
        this.lbl_f = lbl_f;
        final PGC_LabelFixed pgc_LabelFixed6 = lbl_f;
        pnl_coordinates5.add(lbl_f);
        ((GridBagLayout)this.pnl_coordinates.getLayout()).setConstraints(pgc_LabelFixed6, PGC.StdConstraints());
        this.pnl_coordinates.add(this.lbl_f_x = new PGC_LabelFixed(" x= ", new Dimension(22, -1)));
        this.pnl_coordinates.add(this.txt_f_x = new PGC_TextFieldFixed(this.owner, PGC.component_number_text_size));
        this.pnl_coordinates.add(this.lbl_f_y = new PGC_LabelFixed(" y= ", new Dimension(22, -1)));
        this.pnl_coordinates.add(this.txt_f_y = new PGC_TextFieldFixed(this.owner, PGC.component_number_text_size));
        final Panel stdPanel8;
        this.pnl_coordinates.add(stdPanel8 = PGC.StdPanel());
        ((GridBagLayout)this.pnl_coordinates.getLayout()).setConstraints(stdPanel8, PGC.StdConstraintsNewLine());
        final Panel pnl_coordinates6 = this.pnl_coordinates;
        final PGC_LabelFixed lbl_g = new PGC_LabelFixed("g", new Dimension(20, -1));
        this.lbl_g = lbl_g;
        final PGC_LabelFixed pgc_LabelFixed7 = lbl_g;
        pnl_coordinates6.add(lbl_g);
        ((GridBagLayout)this.pnl_coordinates.getLayout()).setConstraints(pgc_LabelFixed7, PGC.StdConstraints());
        this.pnl_coordinates.add(this.lbl_g_x = new PGC_LabelFixed(" x= ", new Dimension(22, -1)));
        this.pnl_coordinates.add(this.txt_g_x = new PGC_TextFieldFixed(this.owner, PGC.component_number_text_size));
        this.pnl_coordinates.add(this.lbl_g_y = new PGC_LabelFixed(" y= ", new Dimension(22, -1)));
        this.pnl_coordinates.add(this.txt_g_y = new PGC_TextFieldFixed(this.owner, PGC.component_number_text_size));
        final Panel stdPanel9;
        this.pnl_coordinates.add(stdPanel9 = PGC.StdPanel());
        ((GridBagLayout)this.pnl_coordinates.getLayout()).setConstraints(stdPanel9, PGC.StdConstraintsNewLine());
        final Panel pnl_coordinates7 = this.pnl_coordinates;
        final PGC_LabelFixed lbl_h = new PGC_LabelFixed("h", new Dimension(20, -1));
        this.lbl_h = lbl_h;
        final PGC_LabelFixed pgc_LabelFixed8 = lbl_h;
        pnl_coordinates7.add(lbl_h);
        ((GridBagLayout)this.pnl_coordinates.getLayout()).setConstraints(pgc_LabelFixed8, PGC.StdConstraints());
        this.pnl_coordinates.add(this.lbl_h_x = new PGC_LabelFixed(" x= ", new Dimension(22, -1)));
        this.pnl_coordinates.add(this.txt_h_x = new PGC_TextFieldFixed(this.owner, PGC.component_number_text_size));
        this.pnl_coordinates.add(this.lbl_h_y = new PGC_LabelFixed(" y= ", new Dimension(22, -1)));
        this.pnl_coordinates.add(this.txt_h_y = new PGC_TextFieldFixed(this.owner, PGC.component_number_text_size));
        final Panel stdPanel10;
        this.pnl_coordinates.add(stdPanel10 = PGC.StdPanel());
        ((GridBagLayout)this.pnl_coordinates.getLayout()).setConstraints(stdPanel10, PGC.StdConstraintsNewLine());
        final Panel pnl_coordinates8 = this.pnl_coordinates;
        final PGC_LabelFixed lbl_k = new PGC_LabelFixed("k", new Dimension(20, -1));
        this.lbl_k = lbl_k;
        final PGC_LabelFixed pgc_LabelFixed9 = lbl_k;
        pnl_coordinates8.add(lbl_k);
        ((GridBagLayout)this.pnl_coordinates.getLayout()).setConstraints(pgc_LabelFixed9, PGC.StdConstraints());
        this.pnl_coordinates.add(this.lbl_k_x = new PGC_LabelFixed(" x= ", new Dimension(22, -1)));
        this.pnl_coordinates.add(this.txt_k_x = new PGC_TextFieldFixed(this.owner, PGC.component_number_text_size));
        this.pnl_coordinates.add(this.lbl_k_y = new PGC_LabelFixed(" y= ", new Dimension(22, -1)));
        this.pnl_coordinates.add(this.txt_k_y = new PGC_TextFieldFixed(this.owner, PGC.component_number_text_size));
        final Panel stdPanel11;
        this.pnl_coordinates.add(stdPanel11 = PGC.StdPanel());
        ((GridBagLayout)this.pnl_coordinates.getLayout()).setConstraints(stdPanel11, PGC.StdConstraintsNewLine());
        final Panel pnl_coordinates9 = this.pnl_coordinates;
        final PGC_LabelFixed lbl_m = new PGC_LabelFixed("m", new Dimension(20, -1));
        this.lbl_m = lbl_m;
        final PGC_LabelFixed pgc_LabelFixed10 = lbl_m;
        pnl_coordinates9.add(lbl_m);
        ((GridBagLayout)this.pnl_coordinates.getLayout()).setConstraints(pgc_LabelFixed10, PGC.StdConstraints());
        this.pnl_coordinates.add(this.lbl_m_x = new PGC_LabelFixed(" x= ", new Dimension(22, -1)));
        this.pnl_coordinates.add(this.txt_m_x = new PGC_TextFieldFixed(this.owner, PGC.component_number_text_size));
        this.pnl_coordinates.add(this.lbl_m_y = new PGC_LabelFixed(" y= ", new Dimension(22, -1)));
        this.pnl_coordinates.add(this.txt_m_y = new PGC_TextFieldFixed(this.owner, PGC.component_number_text_size));
        final Panel stdPanel12;
        this.pnl_coordinates.add(stdPanel12 = PGC.StdPanel());
        ((GridBagLayout)this.pnl_coordinates.getLayout()).setConstraints(stdPanel12, PGC.StdConstraintsNewLine());
        final Panel pnl_coordinates10 = this.pnl_coordinates;
        final PGC_LabelFixed lbl_n = new PGC_LabelFixed("n", new Dimension(20, -1));
        this.lbl_n = lbl_n;
        final PGC_LabelFixed pgc_LabelFixed11 = lbl_n;
        pnl_coordinates10.add(lbl_n);
        ((GridBagLayout)this.pnl_coordinates.getLayout()).setConstraints(pgc_LabelFixed11, PGC.StdConstraints());
        this.pnl_coordinates.add(this.lbl_n_x = new PGC_LabelFixed(" x= ", new Dimension(22, -1)));
        this.pnl_coordinates.add(this.txt_n_x = new PGC_TextFieldFixed(this.owner, PGC.component_number_text_size));
        this.pnl_coordinates.add(this.lbl_n_y = new PGC_LabelFixed(" y= ", new Dimension(22, -1)));
        this.pnl_coordinates.add(this.txt_n_y = new PGC_TextFieldFixed(this.owner, PGC.component_number_text_size));
        final Panel stdPanel13;
        this.pnl_coordinates.add(stdPanel13 = PGC.StdPanel());
        ((GridBagLayout)this.pnl_coordinates.getLayout()).setConstraints(stdPanel13, PGC.StdConstraintsNewLine());
        final Panel stdPanel14;
        final Panel panel2;
        this.pnl_coordinates.add(panel2 = (stdPanel14 = PGC.StdPanel()));
        final GridBagConstraints stdConstraintsNewLine = PGC.StdConstraintsNewLine(new Insets(12, 0, 0, 0));
        stdConstraintsNewLine.fill = 2;
        ((GridBagLayout)this.pnl_coordinates.getLayout()).setConstraints(panel2, stdConstraintsNewLine);
        panel2.setBackground(PGC.color_3d_dark);
        stdPanel14.add(new PGC_LabelFixed(new Dimension(1, 1)));
        final Panel stdPanel15;
        final Panel panel3;
        this.pnl_coordinates.add(panel3 = (stdPanel15 = PGC.StdPanel()));
        final GridBagConstraints stdConstraintsNewLine2 = PGC.StdConstraintsNewLine();
        stdConstraintsNewLine2.fill = 2;
        ((GridBagLayout)this.pnl_coordinates.getLayout()).setConstraints(panel3, stdConstraintsNewLine2);
        panel3.setBackground(PGC.color_3d_light);
        stdPanel15.add(new PGC_LabelFixed(new Dimension(1, 1)));
        final Panel pnl_root2 = this.pnl_root;
        final Panel stdPanel16 = PGC.StdPanel();
        this.pnl_expressions = stdPanel16;
        final Panel panel4 = stdPanel16;
        pnl_root2.add(stdPanel16);
        ((GridBagLayout)this.pnl_root.getLayout()).setConstraints(panel4, PGC.StdConstraintsNewLine(new Insets(5, 5, 5, 5)));
        final Panel stdPanel17;
        this.pnl_expressions.add(stdPanel17 = PGC.StdPanel());
        ((GridBagLayout)this.pnl_expressions.getLayout()).setConstraints(stdPanel17, PGC.StdConstraintsNewLine(new Insets(0, 0, 5, 0)));
        final PGC_LabelFixed pgc_LabelFixed12;
        stdPanel17.add(pgc_LabelFixed12 = new PGC_LabelFixed("Additional user-defined functions", PGC.component_full_text_size));
        ((GridBagLayout)stdPanel17.getLayout()).setConstraints(pgc_LabelFixed12, PGC.StdConstraints());
        final Panel stdPanel18;
        this.pnl_expressions.add(stdPanel18 = PGC.StdPanel());
        ((GridBagLayout)this.pnl_expressions.getLayout()).setConstraints(stdPanel18, PGC.StdConstraintsNewLine());
        final Panel pnl_expressions = this.pnl_expressions;
        final PGC_LabelFixed lbl_h_expr = new PGC_LabelFixed("h", new Dimension(20, -1));
        this.lbl_h_expr = lbl_h_expr;
        final PGC_LabelFixed pgc_LabelFixed13 = lbl_h_expr;
        pnl_expressions.add(lbl_h_expr);
        ((GridBagLayout)this.pnl_expressions.getLayout()).setConstraints(pgc_LabelFixed13, PGC.StdConstraints());
        this.pnl_expressions.add(this.lbl_h_def = new PGC_LabelFixed("= ", new Dimension(12, -1)));
        this.lbl_h_def.setAlignment(2);
        this.pnl_expressions.add(this.txt_h_expr = new PGC_TextFieldFixed(this.owner, PGC.component_wide_text_size));
        final Panel stdPanel19;
        this.pnl_expressions.add(stdPanel19 = PGC.StdPanel());
        ((GridBagLayout)this.pnl_expressions.getLayout()).setConstraints(stdPanel19, PGC.StdConstraintsNewLine());
        final Panel pnl_expressions2 = this.pnl_expressions;
        final PGC_LabelFixed lbl_k_expr = new PGC_LabelFixed("k", new Dimension(20, -1));
        this.lbl_k_expr = lbl_k_expr;
        final PGC_LabelFixed pgc_LabelFixed14 = lbl_k_expr;
        pnl_expressions2.add(lbl_k_expr);
        ((GridBagLayout)this.pnl_expressions.getLayout()).setConstraints(pgc_LabelFixed14, PGC.StdConstraints());
        this.pnl_expressions.add(this.lbl_k_def = new PGC_LabelFixed("= ", new Dimension(12, -1)));
        this.lbl_k_def.setAlignment(2);
        this.pnl_expressions.add(this.txt_k_expr = new PGC_TextFieldFixed(this.owner, PGC.component_wide_text_size));
        final Panel stdPanel20;
        this.pnl_expressions.add(stdPanel20 = PGC.StdPanel());
        ((GridBagLayout)this.pnl_expressions.getLayout()).setConstraints(stdPanel20, PGC.StdConstraintsNewLine());
        final Panel pnl_expressions3 = this.pnl_expressions;
        final PGC_LabelFixed lbl_m_expr = new PGC_LabelFixed("m", new Dimension(20, -1));
        this.lbl_m_expr = lbl_m_expr;
        final PGC_LabelFixed pgc_LabelFixed15 = lbl_m_expr;
        pnl_expressions3.add(lbl_m_expr);
        ((GridBagLayout)this.pnl_expressions.getLayout()).setConstraints(pgc_LabelFixed15, PGC.StdConstraints());
        this.pnl_expressions.add(this.lbl_m_def = new PGC_LabelFixed("= ", new Dimension(12, -1)));
        this.lbl_m_def.setAlignment(2);
        this.pnl_expressions.add(this.txt_m_expr = new PGC_TextFieldFixed(this.owner, PGC.component_wide_text_size));
        final Panel stdPanel21;
        this.pnl_expressions.add(stdPanel21 = PGC.StdPanel());
        ((GridBagLayout)this.pnl_expressions.getLayout()).setConstraints(stdPanel21, PGC.StdConstraintsNewLine());
        final Panel pnl_expressions4 = this.pnl_expressions;
        final PGC_LabelFixed lbl_n_expr = new PGC_LabelFixed("n", new Dimension(20, -1));
        this.lbl_n_expr = lbl_n_expr;
        final PGC_LabelFixed pgc_LabelFixed16 = lbl_n_expr;
        pnl_expressions4.add(lbl_n_expr);
        ((GridBagLayout)this.pnl_expressions.getLayout()).setConstraints(pgc_LabelFixed16, PGC.StdConstraints());
        this.pnl_expressions.add(this.lbl_n_def = new PGC_LabelFixed("= ", new Dimension(12, -1)));
        this.lbl_n_def.setAlignment(2);
        this.pnl_expressions.add(this.txt_n_expr = new PGC_TextFieldFixed(this.owner, PGC.component_wide_text_size));
        final Panel stdPanel22;
        this.pnl_expressions.add(stdPanel22 = PGC.StdPanel());
        ((GridBagLayout)this.pnl_expressions.getLayout()).setConstraints(stdPanel22, PGC.StdConstraintsNewLine());
        final Panel stdPanel23;
        final Panel panel5;
        this.pnl_expressions.add(panel5 = (stdPanel23 = PGC.StdPanel()));
        final GridBagConstraints stdConstraintsNewLine3 = PGC.StdConstraintsNewLine(new Insets(12, 0, 0, 0));
        stdConstraintsNewLine3.fill = 2;
        ((GridBagLayout)this.pnl_expressions.getLayout()).setConstraints(panel5, stdConstraintsNewLine3);
        panel5.setBackground(PGC.color_3d_dark);
        stdPanel23.add(new PGC_LabelFixed(new Dimension(1, 1)));
        final Panel stdPanel24;
        final Panel panel6;
        this.pnl_expressions.add(panel6 = (stdPanel24 = PGC.StdPanel()));
        final GridBagConstraints stdConstraintsNewLine4 = PGC.StdConstraintsNewLine();
        stdConstraintsNewLine4.fill = 2;
        ((GridBagLayout)this.pnl_expressions.getLayout()).setConstraints(panel6, stdConstraintsNewLine4);
        panel6.setBackground(PGC.color_3d_light);
        stdPanel24.add(new PGC_LabelFixed(new Dimension(1, 1)));
        final Panel pnl_root3 = this.pnl_root;
        final Panel stdPanel25 = PGC.StdPanel();
        this.pnl_parametric = stdPanel25;
        final Panel panel7 = stdPanel25;
        pnl_root3.add(stdPanel25);
        ((GridBagLayout)this.pnl_root.getLayout()).setConstraints(panel7, PGC.StdConstraintsNewLine(new Insets(5, 5, 5, 5)));
        final Panel stdPanel26;
        this.pnl_parametric.add(stdPanel26 = PGC.StdPanel());
        ((GridBagLayout)this.pnl_parametric.getLayout()).setConstraints(stdPanel26, PGC.StdConstraintsNewLine(new Insets(0, 0, 5, 0)));
        final PGC_LabelFixed pgc_LabelFixed17;
        stdPanel26.add(pgc_LabelFixed17 = new PGC_LabelFixed("Parametric variable", PGC.component_full_text_size));
        ((GridBagLayout)stdPanel26.getLayout()).setConstraints(pgc_LabelFixed17, PGC.StdConstraints());
        final Panel pnl_parametric = this.pnl_parametric;
        final PGC_LabelFixed lbl_t_min = new PGC_LabelFixed("t = ", new Dimension(22, -1));
        this.lbl_t_min = lbl_t_min;
        final PGC_LabelFixed pgc_LabelFixed18 = lbl_t_min;
        pnl_parametric.add(lbl_t_min);
        ((GridBagLayout)this.pnl_parametric.getLayout()).setConstraints(pgc_LabelFixed18, PGC.StdConstraints());
        this.pnl_parametric.add(this.txt_t_min = new PGC_TextFieldFixed(this.owner, new Dimension(92, -1)));
        final Panel pnl_parametric2 = this.pnl_parametric;
        final PGC_LabelFixed lbl_t_max = new PGC_LabelFixed(" to ", new Dimension(18, -1));
        this.lbl_t_max = lbl_t_max;
        final PGC_LabelFixed pgc_LabelFixed19 = lbl_t_max;
        pnl_parametric2.add(lbl_t_max);
        ((GridBagLayout)this.pnl_parametric.getLayout()).setConstraints(pgc_LabelFixed19, PGC.StdConstraints());
        this.lbl_t_max.setAlignment(1);
        this.pnl_parametric.add(this.txt_t_max = new PGC_TextFieldFixed(this.owner, new Dimension(92, -1)));
        this.pnl_parametric.add(new PGC_LabelFixed("", new Dimension(15, -1)));
        final Panel pnl_parametric3 = this.pnl_parametric;
        final PGC_LabelFixed lbl_t_rep = new PGC_LabelFixed("plot ", new Dimension(35, -1));
        this.lbl_t_rep = lbl_t_rep;
        final PGC_LabelFixed pgc_LabelFixed20 = lbl_t_rep;
        pnl_parametric3.add(lbl_t_rep);
        this.lbl_t_rep.setAlignment(2);
        ((GridBagLayout)this.pnl_parametric.getLayout()).setConstraints(pgc_LabelFixed20, PGC.StdConstraints());
        this.pnl_parametric.add(this.txt_t_rep = new PGC_TextFieldFixed(this.owner, new Dimension(50, -1)));
        this.pnl_parametric.add(new PGC_LabelFixed(" points", new Dimension(60, -1)));
        final Panel stdPanel27;
        this.pnl_parametric.add(stdPanel27 = PGC.StdPanel());
        ((GridBagLayout)this.pnl_parametric.getLayout()).setConstraints(stdPanel27, PGC.StdConstraintsNewLine());
        final Panel pnl_root4 = this.pnl_root;
        final Panel stdPanel28 = PGC.StdPanel();
        this.pnl_error_message = stdPanel28;
        final Panel panel8 = stdPanel28;
        pnl_root4.add(stdPanel28);
        ((GridBagLayout)this.pnl_root.getLayout()).setConstraints(panel8, PGC.StdConstraintsNewLine(new Insets(5, 5, 5, 5)));
        this.pnl_error_message.add(this.lbl_error_message = new PGC_LabelFixed("", PGC.component_full_text_size));
        this.setResizable(false);
        this.pack();
    }
    
    public void init() {
        this.LayoutWindow();
        this.setLayout(new BorderLayout());
        this.add("Center", this.pnl_root);
        this.pack();
    }
    
    public boolean keyDown(final Event event, final int n) {
        boolean keyDown;
        if (n == 10 || n == 27) {
            this.owner.GraphFocus();
            keyDown = true;
        }
        else {
            keyDown = super.keyDown(event, n);
        }
        return keyDown;
    }
    
    public boolean handleEvent(final Event event) {
        if (event.id == 201) {
            if (this.owner != null) {
                this.owner.TextFieldsInput(null);
                this.owner.FrameDestroy(this);
            }
            return true;
        }
        return false;
    }
}
