import java.awt.Component;
import java.awt.Insets;
import java.awt.LayoutManager;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;

// 
// Decompiled by Procyon v0.5.30
// 

class Layout
{
    GridBagLayout appletGBLayout;
    GridBagConstraints appletGBConstr;
    GridBagLayout controlsGBLayout;
    GridBagConstraints controlsGBConstr;
    GridBagLayout timeGBLayout;
    GridBagConstraints timeGBConstr;
    GridBagLayout latGBLayout;
    GridBagConstraints latGBConstr;
    GridBagLayout lonGBLayout;
    GridBagConstraints lonGBConstr;
    GridBagLayout controls2GBLayout;
    GridBagConstraints controls2GBConstr;
    GridBagLayout viewCheckboxPanelLayout;
    GridBagConstraints viewCheckboxPanelGBConstr;
    GridBagLayout dstLayout;
    GridBagConstraints dstGBConstr;
    GridBagLayout locationLayout;
    GridBagConstraints locationGBConstr;
    
    public Layout(final PlanetFinder planetFinder) {
        this.appletGBLayout = new GridBagLayout();
        this.appletGBConstr = new GridBagConstraints();
        this.controlsGBLayout = new GridBagLayout();
        this.controlsGBConstr = new GridBagConstraints();
        this.timeGBLayout = new GridBagLayout();
        this.timeGBConstr = new GridBagConstraints();
        this.latGBLayout = new GridBagLayout();
        this.latGBConstr = new GridBagConstraints();
        this.lonGBLayout = new GridBagLayout();
        this.lonGBConstr = new GridBagConstraints();
        this.controls2GBLayout = new GridBagLayout();
        this.controls2GBConstr = new GridBagConstraints();
        this.viewCheckboxPanelLayout = new GridBagLayout();
        this.viewCheckboxPanelGBConstr = new GridBagConstraints();
        this.dstLayout = new GridBagLayout();
        this.dstGBConstr = new GridBagConstraints();
        this.locationLayout = new GridBagLayout();
        this.locationGBConstr = new GridBagConstraints();
        planetFinder.removeAll();
        planetFinder.controls.removeAll();
        planetFinder.controls2.removeAll();
        planetFinder.timePanel.removeAll();
        planetFinder.dstPanel.removeAll();
        planetFinder.locationPanel.removeAll();
        planetFinder.setLayout(this.appletGBLayout);
        this.appletGBConstr.insets = new Insets(2, 2, 2, 2);
        this.appletGBConstr.fill = 1;
        this.appletGBConstr.gridx = 1;
        this.appletGBConstr.gridy = 0;
        this.appletGBConstr.gridwidth = 1;
        this.appletGBConstr.gridheight = 1;
        this.appletGBConstr.weightx = 1.0;
        this.appletGBConstr.weighty = 1.0;
        planetFinder.add(planetFinder.sky, this.appletGBConstr);
        this.appletGBConstr.fill = 0;
        this.appletGBConstr.gridx = 0;
        this.appletGBConstr.gridy = 0;
        this.appletGBConstr.gridwidth = 1;
        this.appletGBConstr.gridheight = 1;
        this.appletGBConstr.weightx = 0.0;
        this.appletGBConstr.weighty = 0.0;
        planetFinder.add(planetFinder.controls, this.appletGBConstr);
        this.appletGBConstr.fill = 2;
        this.appletGBConstr.gridx = 0;
        this.appletGBConstr.gridy = 1;
        this.appletGBConstr.gridwidth = 2;
        this.appletGBConstr.gridheight = 1;
        this.appletGBConstr.weightx = 0.0;
        this.appletGBConstr.weighty = 0.0;
        this.appletGBConstr.weightx = 1.0;
        planetFinder.add(planetFinder.controls2, this.appletGBConstr);
        planetFinder.controls.setLayout(this.controlsGBLayout);
        this.controlsGBConstr.fill = 0;
        this.controlsGBConstr.gridx = 0;
        this.controlsGBConstr.gridy = 0;
        this.controlsGBConstr.gridwidth = 3;
        this.controlsGBConstr.gridheight = 1;
        planetFinder.controls.add(planetFinder.timePanel, this.controlsGBConstr);
        this.controlsGBConstr.fill = 0;
        this.controlsGBConstr.gridx = 0;
        this.controlsGBConstr.gridy = 1;
        this.controlsGBConstr.gridwidth = 3;
        this.controlsGBConstr.gridheight = 1;
        planetFinder.controls.add(planetFinder.dstPanel, this.controlsGBConstr);
        this.controlsGBConstr.fill = 0;
        this.controlsGBConstr.gridx = 0;
        this.controlsGBConstr.gridy = 2;
        this.controlsGBConstr.gridwidth = 1;
        this.controlsGBConstr.gridheight = 1;
        planetFinder.controls.add(planetFinder.dayText, this.controlsGBConstr);
        this.controlsGBConstr.fill = 0;
        this.controlsGBConstr.gridx = 1;
        this.controlsGBConstr.gridy = 2;
        this.controlsGBConstr.gridwidth = 1;
        this.controlsGBConstr.gridheight = 1;
        planetFinder.controls.add(planetFinder.monthChoice, this.controlsGBConstr);
        this.controlsGBConstr.fill = 0;
        this.controlsGBConstr.gridx = 2;
        this.controlsGBConstr.gridy = 2;
        this.controlsGBConstr.gridwidth = 1;
        this.controlsGBConstr.gridheight = 1;
        planetFinder.controls.add(planetFinder.yearText, this.controlsGBConstr);
        this.controlsGBConstr.fill = 0;
        this.controlsGBConstr.gridx = 0;
        this.controlsGBConstr.gridy = 6;
        this.controlsGBConstr.gridwidth = 3;
        this.controlsGBConstr.gridheight = 1;
        planetFinder.controls.add(planetFinder.locationPanel, this.controlsGBConstr);
        this.controlsGBConstr.fill = 0;
        this.controlsGBConstr.gridx = 0;
        this.controlsGBConstr.gridy = 7;
        this.controlsGBConstr.gridwidth = 2;
        this.controlsGBConstr.gridheight = 1;
        planetFinder.controls.add(planetFinder.nakedEyeOnlyCheckbox, this.controlsGBConstr);
        planetFinder.controls2.setLayout(this.controls2GBLayout);
        this.controls2GBConstr.fill = 2;
        this.controls2GBConstr.gridx = 0;
        this.controls2GBConstr.gridy = 0;
        this.controls2GBConstr.gridwidth = 1;
        this.controls2GBConstr.gridheight = 1;
        this.controls2GBConstr.weightx = 1.0;
        planetFinder.controls2.add(planetFinder.viewCheckboxPanel, this.controls2GBConstr);
        this.controls2GBConstr.fill = 2;
        this.controls2GBConstr.gridx = 0;
        this.controls2GBConstr.gridy = 1;
        this.controls2GBConstr.gridwidth = 1;
        this.controls2GBConstr.gridheight = 1;
        this.controls2GBConstr.weightx = 1.0;
        planetFinder.controls2.add(planetFinder.homePageAndAuthorStaticText, this.controls2GBConstr);
        this.controls2GBConstr.fill = 2;
        this.controls2GBConstr.gridx = 0;
        this.controls2GBConstr.gridy = 3;
        this.controls2GBConstr.gridwidth = 1;
        this.controls2GBConstr.gridheight = 1;
        this.controls2GBConstr.weightx = 1.0;
        planetFinder.controls2.add(planetFinder.homePageAndAuthor2StaticText, this.controls2GBConstr);
        planetFinder.locationPanel.setLayout(this.locationLayout);
        this.locationGBConstr.fill = 0;
        this.locationGBConstr.gridx = 0;
        this.locationGBConstr.gridy = 0;
        this.locationGBConstr.gridwidth = 1;
        this.locationGBConstr.gridheight = 1;
        this.locationGBConstr.anchor = 17;
        planetFinder.locationPanel.add(planetFinder.cityChoice, this.locationGBConstr);
        this.locationGBConstr.fill = 0;
        this.locationGBConstr.gridx = 0;
        this.locationGBConstr.gridy = 1;
        this.locationGBConstr.gridwidth = 1;
        this.locationGBConstr.gridheight = 1;
        this.locationGBConstr.anchor = 17;
        planetFinder.locationPanel.add(planetFinder.latPanel, this.locationGBConstr);
        this.locationGBConstr.fill = 0;
        this.locationGBConstr.gridx = 0;
        this.locationGBConstr.gridy = 2;
        this.locationGBConstr.gridwidth = 1;
        this.locationGBConstr.gridheight = 1;
        this.locationGBConstr.anchor = 17;
        planetFinder.locationPanel.add(planetFinder.lonPanel, this.locationGBConstr);
        planetFinder.viewCheckboxPanel.setLayout(this.viewCheckboxPanelLayout);
        this.viewCheckboxPanelGBConstr.fill = 0;
        this.viewCheckboxPanelGBConstr.gridx = 0;
        this.viewCheckboxPanelGBConstr.gridy = 0;
        this.viewCheckboxPanelGBConstr.gridwidth = 1;
        this.viewCheckboxPanelGBConstr.gridheight = 1;
        planetFinder.viewCheckboxPanel.add(planetFinder.skyCheckbox, this.viewCheckboxPanelGBConstr);
        this.viewCheckboxPanelGBConstr.fill = 0;
        this.viewCheckboxPanelGBConstr.gridx = 1;
        this.viewCheckboxPanelGBConstr.gridy = 0;
        this.viewCheckboxPanelGBConstr.gridwidth = 1;
        this.viewCheckboxPanelGBConstr.gridheight = 1;
        planetFinder.viewCheckboxPanel.add(planetFinder.innerSolarSystemCheckbox, this.viewCheckboxPanelGBConstr);
        this.viewCheckboxPanelGBConstr.fill = 0;
        this.viewCheckboxPanelGBConstr.gridx = 2;
        this.viewCheckboxPanelGBConstr.gridy = 0;
        this.viewCheckboxPanelGBConstr.gridwidth = 1;
        this.viewCheckboxPanelGBConstr.gridheight = 1;
        planetFinder.viewCheckboxPanel.add(planetFinder.outerSolarSystemCheckbox, this.viewCheckboxPanelGBConstr);
        planetFinder.timePanel.setLayout(this.timeGBLayout);
        this.timeGBConstr.fill = 0;
        this.timeGBConstr.gridx = 0;
        this.timeGBConstr.gridy = 0;
        this.timeGBConstr.gridwidth = 1;
        this.timeGBConstr.gridheight = 1;
        planetFinder.timePanel.add(planetFinder.localTimeStaticText, this.timeGBConstr);
        this.timeGBConstr.fill = 0;
        this.timeGBConstr.gridx = 1;
        this.timeGBConstr.gridy = 0;
        this.timeGBConstr.gridwidth = 1;
        this.timeGBConstr.gridheight = 1;
        planetFinder.timePanel.add(planetFinder.hourText, this.timeGBConstr);
        this.timeGBConstr.fill = 0;
        this.timeGBConstr.gridx = 2;
        this.timeGBConstr.gridy = 0;
        this.timeGBConstr.gridwidth = 1;
        this.timeGBConstr.gridheight = 1;
        planetFinder.timePanel.add(new StaticText(":"), this.timeGBConstr);
        this.timeGBConstr.fill = 0;
        this.timeGBConstr.gridx = 3;
        this.timeGBConstr.gridy = 0;
        this.timeGBConstr.gridwidth = 1;
        this.timeGBConstr.gridheight = 1;
        planetFinder.timePanel.add(planetFinder.minuteText, this.timeGBConstr);
        this.timeGBConstr.fill = 0;
        this.timeGBConstr.gridx = 0;
        this.timeGBConstr.gridy = 1;
        this.timeGBConstr.gridwidth = 2;
        this.timeGBConstr.gridheight = 1;
        planetFinder.timePanel.add(planetFinder.timeZoneLabel, this.timeGBConstr);
        this.timeGBConstr.fill = 0;
        this.timeGBConstr.gridx = 3;
        this.timeGBConstr.gridy = 1;
        this.timeGBConstr.gridwidth = 2;
        this.timeGBConstr.gridheight = 1;
        planetFinder.timePanel.add(planetFinder.timeZoneText, this.timeGBConstr);
        planetFinder.dstPanel.setLayout(this.dstLayout);
        this.dstGBConstr.fill = 0;
        this.dstGBConstr.gridx = 0;
        this.dstGBConstr.gridy = 0;
        this.dstGBConstr.gridwidth = 1;
        this.dstGBConstr.gridheight = 1;
        planetFinder.dstPanel.add(planetFinder.dstCheckbox, this.dstGBConstr);
        this.dstGBConstr.fill = 0;
        this.dstGBConstr.gridx = 1;
        this.dstGBConstr.gridy = 0;
        this.dstGBConstr.gridwidth = 1;
        this.dstGBConstr.gridheight = 1;
        planetFinder.dstPanel.add(planetFinder.dstAutoCheckbox, this.dstGBConstr);
        this.dstGBConstr.fill = 0;
        this.dstGBConstr.gridx = 2;
        this.dstGBConstr.gridy = 0;
        this.dstGBConstr.gridwidth = 1;
        this.dstGBConstr.gridheight = 1;
        planetFinder.dstPanel.add(planetFinder.dstManualCheckbox, this.dstGBConstr);
        planetFinder.latPanel.setLayout(this.latGBLayout);
        this.latGBConstr.fill = 0;
        this.latGBConstr.gridx = 0;
        this.latGBConstr.gridy = 0;
        this.latGBConstr.gridwidth = 1;
        this.latGBConstr.gridheight = 1;
        planetFinder.latPanel.add(planetFinder.latitudeStaticText, this.latGBConstr);
        this.latGBConstr.fill = 0;
        this.latGBConstr.gridx = 1;
        this.latGBConstr.gridy = 0;
        this.latGBConstr.gridwidth = 1;
        this.latGBConstr.gridheight = 1;
        planetFinder.latPanel.add(planetFinder.yourLatText, this.latGBConstr);
        this.latGBConstr.fill = 0;
        this.latGBConstr.gridx = 2;
        this.latGBConstr.gridy = 0;
        this.latGBConstr.gridwidth = 1;
        this.latGBConstr.gridheight = 1;
        planetFinder.latPanel.add(planetFinder.latNCheckbox, this.latGBConstr);
        this.latGBConstr.fill = 0;
        this.latGBConstr.gridx = 3;
        this.latGBConstr.gridy = 0;
        this.latGBConstr.gridwidth = 1;
        this.latGBConstr.gridheight = 1;
        planetFinder.latPanel.add(planetFinder.latSCheckbox, this.latGBConstr);
        planetFinder.lonPanel.setLayout(this.lonGBLayout);
        this.lonGBConstr.fill = 0;
        this.lonGBConstr.gridx = 0;
        this.lonGBConstr.gridy = 0;
        this.lonGBConstr.gridwidth = 1;
        this.lonGBConstr.gridheight = 1;
        planetFinder.lonPanel.add(planetFinder.longitudeStaticText);
        this.lonGBConstr.fill = 0;
        this.lonGBConstr.gridx = 1;
        this.lonGBConstr.gridy = 0;
        this.lonGBConstr.gridwidth = 1;
        this.lonGBConstr.gridheight = 1;
        planetFinder.lonPanel.add(planetFinder.yourLongText, this.lonGBConstr);
        this.lonGBConstr.fill = 0;
        this.lonGBConstr.gridx = 2;
        this.lonGBConstr.gridy = 0;
        this.lonGBConstr.gridwidth = 1;
        this.lonGBConstr.gridheight = 1;
        planetFinder.lonPanel.add(planetFinder.lonECheckbox, this.lonGBConstr);
        this.lonGBConstr.fill = 0;
        this.lonGBConstr.gridx = 3;
        this.lonGBConstr.gridy = 0;
        this.lonGBConstr.gridwidth = 1;
        this.lonGBConstr.gridheight = 1;
        planetFinder.lonPanel.add(planetFinder.lonWCheckbox, this.lonGBConstr);
    }
}
