// 
// Decompiled by Procyon v0.5.30
// 

class Text
{
    public Language lang;
    public String daylightSavings;
    public String auto;
    public String manual;
    public String northLetter;
    public String southLetter;
    public String eastLetter;
    public String westLetter;
    public String sky;
    public String innerSolarSystem;
    public String outerSolarSystem;
    public String update;
    public String nakedEyePlanetsOnly;
    public String timeZone;
    public String[] monthNames;
    public String[] planetNames;
    public String sun;
    public String moon;
    public String latitude;
    public String longitude;
    public String localTime;
    private static final String aGrave = "\u00e0";
    private static final String eGrave = "\u00e8";
    private static final String aAcute = "\u00e1";
    private static final String eAcute = "\u00e9";
    private static final String iAcute = "\u00ed";
    private static final String uAcute = "\u00fa";
    private static final String oAcute = "\u00f3";
    private static final String aTilde = "\u00e3";
    private static final String aUmlaut = "\u00e4";
    private static final String oUmlaut = "\u00f6";
    private static final String uUmlaut = "\u00fc";
    private static final String aUmlautUC = "\u00c4";
    private static final String oUmlautUC = "\u00d6";
    private static final String uUmlautUC = "\u00dc";
    private static final String aRing = "\u00e5";
    
    public Text(final Language lang) {
        this.monthNames = new String[12];
        this.planetNames = new String[9];
        this.lang = lang;
        if (lang.equals(new Language("fr"))) {
            this.daylightSavings = "Heure d'\u00e9t\u00e9";
            this.auto = "Auto";
            this.manual = "Manuel";
            this.northLetter = "N";
            this.southLetter = "S";
            this.eastLetter = "E";
            this.westLetter = "O";
            this.sky = "Ciel";
            this.innerSolarSystem = "Vue des plan\u00e8tes int\u00e9rieures";
            this.outerSolarSystem = "Vue des plan\u00e8tes ext\u00e9rieures";
            this.update = "Mettre \u00e0 jour";
            this.nakedEyePlanetsOnly = "Plan\u00e8tes visibles \u00e0 l'oeil nu";
            this.timeZone = "Fuseau horaire";
            this.monthNames[0] = "Jan";
            this.monthNames[3] = "Avr";
            this.monthNames[6] = "Juil";
            this.monthNames[9] = "Oct";
            this.monthNames[1] = "F\u00e9v";
            this.monthNames[4] = "Mai";
            this.monthNames[7] = "Aug";
            this.monthNames[10] = "Nov";
            this.monthNames[2] = "Mar";
            this.monthNames[5] = "Juin";
            this.monthNames[8] = "Sep";
            this.monthNames[11] = "D\u00e9c";
            this.planetNames[0] = "Mercure";
            this.planetNames[3] = "Mars";
            this.planetNames[6] = "Uranus";
            this.planetNames[1] = "V\u00e9nus";
            this.planetNames[4] = "Jupiter";
            this.planetNames[7] = "Neptune";
            this.planetNames[2] = "Terre";
            this.planetNames[5] = "Saturne";
            this.planetNames[8] = "Pluton";
            this.sun = "Soleil";
            this.moon = "Lune";
            this.latitude = "Latitude";
            this.longitude = "Longitude";
            this.localTime = "Temps local";
            return;
        }
        if (lang.equals(new Language("de"))) {
            this.daylightSavings = "Sommerzeit";
            this.auto = "automatisch";
            this.manual = "manuell";
            this.northLetter = "N";
            this.southLetter = "S";
            this.eastLetter = "O";
            this.westLetter = "W";
            this.sky = "Himmel";
            this.innerSolarSystem = "Inneres Sonnensystem";
            this.outerSolarSystem = "\u00c4usseres Sonnensystem";
            this.update = "Aktualisieren";
            this.nakedEyePlanetsOnly = "Planeten welche mit blossem Auge sichtbar sind";
            this.timeZone = "Zeitzone";
            this.monthNames[0] = "Jan";
            this.monthNames[3] = "Apr";
            this.monthNames[6] = "Jul";
            this.monthNames[9] = "Okt";
            this.monthNames[1] = "Feb";
            this.monthNames[4] = "Mai";
            this.monthNames[7] = "Aug";
            this.monthNames[10] = "Nov";
            this.monthNames[2] = "M\u00e4r";
            this.monthNames[5] = "Jun";
            this.monthNames[8] = "Sep";
            this.monthNames[11] = "Dez";
            this.planetNames[0] = "Merkur";
            this.planetNames[3] = "Mars";
            this.planetNames[6] = "Uranus";
            this.planetNames[1] = "Venus";
            this.planetNames[4] = "Jupiter";
            this.planetNames[7] = "Neptun";
            this.planetNames[2] = "Erde";
            this.planetNames[5] = "Saturn";
            this.planetNames[8] = "Pluto";
            this.sun = "Sonne";
            this.moon = "Mond";
            this.latitude = "Breite";
            this.longitude = "L\u00e4nge";
            this.localTime = "Lokalzeit";
            return;
        }
        if (lang.equals(new Language("es"))) {
            this.daylightSavings = "Hora de verano";
            this.auto = "Auto";
            this.manual = "Manual";
            this.northLetter = "N";
            this.southLetter = "S";
            this.eastLetter = "E";
            this.westLetter = "O";
            this.sky = "Cielo";
            this.innerSolarSystem = "Mapa de los planetas interiores";
            this.outerSolarSystem = "Mapa de los planetas exteriores";
            this.update = "Actualizar";
            this.nakedEyePlanetsOnly = "S\u00f3lo los planetas visibles sin telescopio";
            this.timeZone = "Zona horaria";
            this.monthNames[0] = "Ene";
            this.monthNames[3] = "Abr";
            this.monthNames[6] = "Jul";
            this.monthNames[9] = "Oct";
            this.monthNames[1] = "Feb";
            this.monthNames[4] = "May";
            this.monthNames[7] = "Ago";
            this.monthNames[10] = "Nov";
            this.monthNames[2] = "Mar";
            this.monthNames[5] = "Jun";
            this.monthNames[8] = "Sep";
            this.monthNames[11] = "Dic";
            this.planetNames[0] = "Mercurio";
            this.planetNames[3] = "Marte";
            this.planetNames[6] = "Urano";
            this.planetNames[1] = "Venus";
            this.planetNames[4] = "J\u00fapiter";
            this.planetNames[7] = "Neptuno";
            this.planetNames[2] = "Terra";
            this.planetNames[5] = "Saturno";
            this.planetNames[8] = "Plut\u00f3n";
            this.sun = "Sol";
            this.moon = "Luna";
            this.latitude = "Latitud";
            this.longitude = "Longitud";
            this.localTime = "Hora local";
            return;
        }
        if (lang.equals(new Language("ar"))) {
            this.daylightSavings = "\u062a\u0648\u0642\u064a\u062a \u0635\u064a\u0641\u064a";
            this.auto = "\u0622\u0644\u064a";
            this.manual = "\u064a\u062f\u0648\u064a";
            this.northLetter = "\u0634";
            this.southLetter = "\u062c";
            this.eastLetter = "\u0642";
            this.westLetter = "\u063a";
            this.sky = "\u0627\u0644\u0633\u0645\u0627\u0621";
            this.innerSolarSystem = "\u0627\u0644\u0646\u0638\u0627\u0645 \u0627\u0644\u0634\u0645\u0633\u064a \u0627\u0644\u062f\u0627\u062e\u0644\u064a";
            this.outerSolarSystem = "\u0627\u0644\u0646\u0638\u0627\u0645 \u0627\u0644\u0634\u0645\u0633\u064a \u0627\u0644\u062e\u0627\u0631\u062c\u064a";
            this.update = "\u062a\u062d\u062f\u064a\u062b";
            this.nakedEyePlanetsOnly = "\u0643\u0648\u0627\u0643\u0628 \u062a\u0631\u0649 \u0628\u0627\u0644\u0639\u064a\u0646 \u0627\u0644\u0645\u062c\u0631\u062f\u0629 \u0641\u0642\u0637";
            this.timeZone = "\u0627\u0644\u062a\u0648\u0642\u064a\u062a";
            this.monthNames[0] = "\u064a\u0646\u0627\u064a\u0631";
            this.monthNames[1] = "\u0641\u0628\u0631\u0627\u064a\u0631";
            this.monthNames[2] = "\u0645\u0627\u0631\u0633";
            this.monthNames[3] = "\u0625\u0628\u0631\u064a\u0644";
            this.monthNames[4] = "\u0645\u0627\u064a\u0648";
            this.monthNames[5] = "\u064a\u0648\u0646\u064a\u0648";
            this.monthNames[6] = "\u064a\u0648\u0644";
            this.monthNames[7] = "\u0623\u063a\u0633\u0637\u0633";
            this.monthNames[8] = "\u0633\u0628\u062a\u0645\u0628\u0631";
            this.monthNames[9] = "\u0623\u0643\u062a\u0648\u0628\u0631";
            this.monthNames[10] = "\u0646\u0648\u0641\u0645\u0628\u0631";
            this.monthNames[11] = "\u062f\u064a\u0633\u0645\u0628\u0631";
            this.planetNames[0] = "\u0639\u0637\u0627\u0631\u062f";
            this.planetNames[1] = "\u0627\u0644\u0632\u0647\u0631\u0629";
            this.planetNames[2] = "\u0627\u0644\u0623\u0631\u0636";
            this.planetNames[3] = "\u0627\u0644\u0645\u0631\u064a\u062e";
            this.planetNames[4] = "\u0627\u0644\u0645\u0634\u062a\u0631\u064a";
            this.planetNames[5] = "\u0632\u062d\u0644";
            this.planetNames[6] = "\u064a\u0648\u0631\u0627\u0646\u0648\u0633";
            this.planetNames[7] = "\u0646\u0628\u062a\u0648\u0646";
            this.planetNames[8] = "\u0628\u0644\u0648\u062a\u0648";
            this.sun = "\u0627\u0644\u0634\u0645\u0633";
            this.moon = "\u0627\u0644\u0642\u0645\u0631";
            this.latitude = "\u0627\u0644\u0637\u0648\u0644";
            this.longitude = "\u0627\u0644\u0639\u0631\u0636";
            this.localTime = "\u0627\u0644\u062a\u0648\u0642\u064a\u062a \u0627\u0644\u0645\u062d\u0644\u064a";
            return;
        }
        if (lang.equals(new Language("ja"))) {
            this.daylightSavings = "\u590f\u6642\u9593\u8abf\u6574";
            this.auto = "\u81ea\u52d5";
            this.manual = "\u624b\u52d5";
            this.northLetter = "\u5317";
            this.southLetter = "\u5357";
            this.eastLetter = "\u6771";
            this.westLetter = "\u897f";
            this.sky = "\u7a7a";
            this.innerSolarSystem = "\u5185\u5074\u306e\u592a\u967d\u7cfb";
            this.outerSolarSystem = "\u5916\u5074\u306e\u592a\u967d\u7cfb";
            this.update = "\u66f4\u65b0";
            this.nakedEyePlanetsOnly = "\u8089\u773c\u60d1\u661f\u306e\u307f";
            this.timeZone = "\u6642\u9593\u5e2f";
            this.monthNames[0] = "\uff11\u6708";
            this.monthNames[3] = "\uff14\u6708";
            this.monthNames[6] = "\uff17\u6708";
            this.monthNames[9] = "\uff11\uff10\u6708";
            this.monthNames[1] = "\uff12\u6708";
            this.monthNames[4] = "\uff15\u6708";
            this.monthNames[7] = "\uff18\u6708";
            this.monthNames[10] = "\uff11\uff11\u6708";
            this.monthNames[2] = "\uff13\u6708";
            this.monthNames[5] = "\uff16\u6708";
            this.monthNames[8] = "\uff19\u6708";
            this.monthNames[11] = "\uff11\uff12\u6708";
            this.planetNames[0] = "\u6c34\u661f";
            this.planetNames[3] = "\u706b\u661f";
            this.planetNames[6] = "\u5929\u738b\u661f";
            this.planetNames[1] = "\u91d1\u661f";
            this.planetNames[4] = "\u6728\u661f";
            this.planetNames[7] = "\u6d77\u738b\u661f";
            this.planetNames[2] = "\u5730\u7403";
            this.planetNames[5] = "\u571f\u661f";
            this.planetNames[8] = "\u51a5\u738b\u661f";
            this.sun = "\u592a\u967d";
            this.moon = "\u6708";
            this.latitude = "\u7def\u5ea6";
            this.longitude = "\u7d4c\u5ea6";
            this.localTime = "\u73fe\u5730\u6642\u523b";
            return;
        }
        if (lang.equals(new Language("el"))) {
            this.daylightSavings = "\u03a9\u03c1\u03b1 \u03ba\u03b1\u03bb\u03bf\u03ba\u03b1\u03b9'\u03c1\u03b7\u03c3";
            this.auto = "\u0391\u03c5\u03c4\u03bf";
            this.manual = "\u03a7\u03b5\u03b9\u03c1\u03c9\u03bd\u03b1\u03ba\u03c4\u03b9\u03ba\u00f3\u03c2";
            this.northLetter = "\u0392";
            this.southLetter = "\u039d";
            this.eastLetter = "\u0391";
            this.westLetter = "\u0394";
            this.sky = "\u039f\u03c5\u03c1\u03b1\u03bd\u00f3\u03c2";
            this.innerSolarSystem = "\u03a7\u00e1\u03c1\u03c4\u03b7\u03c2 \u03c4\u03c9\u03bd \u03c0\u03bb\u03b1\u03bd\u03b7\u03c4\u03c9\u03bd \u03b5\u03c3\u03c9\u03c4\u03b5\u03c1\u03b9\u03ba\u03c9\u03bd";
            this.outerSolarSystem = "\u03a7\u00e1\u03c1\u03c4\u03b7\u03c2 \u03c4\u03c9\u03bd \u03c0\u03bb\u03b1\u03bd\u03b7\u03c4\u03c9\u03bd \u03b5\u03be\u03c9\u03c4\u03b5\u03c1\u03b9\u03ba\u03c9\u03bd";
            this.update = "\u0395\u03bd\u03b7\u03bc\u03b5'\u03c1\u03c9\u03bd\u03b5";
            this.nakedEyePlanetsOnly = "\u03a0\u03bb\u03b1\u03bd\u03b7'\u03c4\u03b5\u03c2 \u03bf\u03c1\u03b1\u03c4\u03b5'\u03c2 \u03c7\u03bf\u03c1\u03b9'\u03c2 \u03c4\u03b7\u03bb\u03b5\u03c3\u03ba\u03bf'\u03c0\u03b9\u03bf";
            this.timeZone = "\u0391\u03c4\u03c1\u03b1\u03ba\u03c4\u03bf\u03c2 \u03c7\u03c1\u03bf\u03bd\u03bf\u03c5";
            this.monthNames[0] = "\u0399\u03b1\u03bd";
            this.monthNames[3] = "\u0391\u03c0\u03c1";
            this.monthNames[6] = "\u0399\u03c5\u03bb";
            this.monthNames[9] = "\u039f\u03ba\u03c4";
            this.monthNames[1] = "\u03a6\u03b5\u03b2";
            this.monthNames[4] = "\u039c\u00e1\u03b9";
            this.monthNames[7] = "\u0391\u03c5\u03b3";
            this.monthNames[10] = "\u039d\u03bf\u03b5";
            this.monthNames[2] = "\u039c\u03b1\u03c1";
            this.monthNames[5] = "\u0399\u03c5\u03bd";
            this.monthNames[8] = "\u03a3\u03b5\u03c0";
            this.monthNames[11] = "\u0394\u03b5\u03ba";
            this.planetNames[0] = "\u0397\u03c1\u03bc\u03b7\u03c3";
            this.planetNames[3] = "\u0391\u03c1\u03b7\u03c2";
            this.planetNames[6] = "\u039f\u03c5\u03c1\u03b1\u03bd\u03bf\u03c2";
            this.planetNames[1] = "\u0391\u03c6\u03c1\u03bf\u03b4\u03b9\u03c4\u03b7\u03c2";
            this.planetNames[4] = "\u0396\u03b5\u03c5\u03c3";
            this.planetNames[7] = "\u03a0\u03bf\u03c3\u03b5\u03b9\u03b4\u03bf\u03bd";
            this.planetNames[2] = "\u0393\u03b7";
            this.planetNames[5] = "K\u03c1\u03bf\u03bd\u03bf\u03c2";
            this.planetNames[8] = "\u03a0\u03bb\u03c5\u03c4\u03bf";
            this.sun = "\u0397\u03bb\u03b9\u03bf\u03c2";
            this.moon = "\u03a3\u03b5\u03bb\u03b7'\u03bd\u03b7";
            this.latitude = "\u0393\u03b5\u03c9\u03b3\u03c1\u03b1\u03c6\u03b9\u03ba\u00f3 \u03b7\u03bb\u00e1\u03c4\u03bf\u03c2";
            this.longitude = "\u039c\u03b7'\u03ba\u03bf\u03c2";
            this.localTime = "\u03a4\u03bf\u03c0\u03b9\u03ba\u03b7' \u03c9'\u03c1\u03b1";
            return;
        }
        if (lang.equals(new Language("da"))) {
            this.daylightSavings = "Sommertid";
            this.auto = "Auto";
            this.manual = "Manuelt";
            this.northLetter = "N";
            this.southLetter = "S";
            this.eastLetter = "\u00d8";
            this.westLetter = "V";
            this.sky = "Stjernehimlen";
            this.innerSolarSystem = "Indre solsystem";
            this.outerSolarSystem = "Ydre solsystem";
            this.update = "Opdater";
            this.nakedEyePlanetsOnly = "Kun planeter synlige med blotte \u00f8je";
            this.timeZone = "Tidszone";
            this.monthNames[0] = "Jan";
            this.monthNames[3] = "Apr";
            this.monthNames[6] = "Jul";
            this.monthNames[9] = "Okt";
            this.monthNames[1] = "Feb";
            this.monthNames[4] = "Maj";
            this.monthNames[7] = "Aug";
            this.monthNames[10] = "Nov";
            this.monthNames[2] = "Mar";
            this.monthNames[5] = "Jun";
            this.monthNames[8] = "Sep";
            this.monthNames[11] = "Dec";
            this.planetNames[0] = "Merkur";
            this.planetNames[3] = "Mars";
            this.planetNames[6] = "Uranus";
            this.planetNames[1] = "Venus";
            this.planetNames[4] = "Jupiter";
            this.planetNames[7] = "Neptun";
            this.planetNames[2] = "Jorden";
            this.planetNames[5] = "Saturn";
            this.planetNames[8] = "Pluto";
            this.sun = "Solen";
            this.moon = "M\u00e5nen";
            this.latitude = "Breddegrad";
            this.longitude = "L\u00e6ngdegrad";
            this.localTime = "Lokal tid";
            return;
        }
        if (lang.equals(new Language("sv"))) {
            this.daylightSavings = "Sommartid";
            this.auto = "Auto";
            this.manual = "Manuell";
            this.northLetter = "N";
            this.southLetter = "S";
            this.eastLetter = "\u00d6";
            this.westLetter = "V";
            this.sky = "Stj\u00e4rnhimlen";
            this.innerSolarSystem = "Inre solsystemet";
            this.outerSolarSystem = "Yttre solsystemet";
            this.update = "Opdater";
            this.nakedEyePlanetsOnly = "Endast planeter synliga med blotta \u00f6gat";
            this.timeZone = "Tidzon";
            this.monthNames[0] = "Jan";
            this.monthNames[3] = "Apr";
            this.monthNames[6] = "Jul";
            this.monthNames[9] = "Okt";
            this.monthNames[1] = "Feb";
            this.monthNames[4] = "Maj";
            this.monthNames[7] = "Aug";
            this.monthNames[10] = "Nov";
            this.monthNames[2] = "Mar";
            this.monthNames[5] = "Jun";
            this.monthNames[8] = "Sep";
            this.monthNames[11] = "Dec";
            this.planetNames[0] = "Merkurius";
            this.planetNames[3] = "Mars";
            this.planetNames[6] = "Uranus";
            this.planetNames[1] = "Venus";
            this.planetNames[4] = "Jupiter";
            this.planetNames[7] = "Neptunus";
            this.planetNames[2] = "Jorden";
            this.planetNames[5] = "Saturnus";
            this.planetNames[8] = "Pluto";
            this.sun = "Solen";
            this.moon = "M\u00e5nen";
            this.latitude = "Latitud";
            this.longitude = "Longitud";
            this.localTime = "Lokaltid";
            return;
        }
        if (lang.equals(new Language("it"))) {
            this.daylightSavings = "Ora legale";
            this.auto = "Auto";
            this.manual = "Manuale";
            this.northLetter = "N";
            this.southLetter = "S";
            this.eastLetter = "E";
            this.westLetter = "O";
            this.sky = "Cielo";
            this.innerSolarSystem = "Sistema solare interno ";
            this.outerSolarSystem = "Sistema solare esterno";
            this.update = "Aggiorna";
            this.nakedEyePlanetsOnly = "Solo i pianeti visibili a occhio nudo";
            this.timeZone = "Fuso orario";
            this.monthNames[0] = "Gen";
            this.monthNames[3] = "Apr";
            this.monthNames[6] = "Lug";
            this.monthNames[9] = "Ott";
            this.monthNames[1] = "Feb";
            this.monthNames[4] = "Mag";
            this.monthNames[7] = "Ago";
            this.monthNames[10] = "Nov";
            this.monthNames[2] = "Mar";
            this.monthNames[5] = "Giu";
            this.monthNames[8] = "Set";
            this.monthNames[11] = "Dic";
            this.planetNames[0] = "Mercurio";
            this.planetNames[3] = "Marte";
            this.planetNames[6] = "Urano";
            this.planetNames[1] = "Venere";
            this.planetNames[4] = "Giove";
            this.planetNames[7] = "Nettuno";
            this.planetNames[2] = "Terra";
            this.planetNames[5] = "Saturno";
            this.planetNames[8] = "Plutone";
            this.sun = "Sole";
            this.moon = "Luna";
            this.latitude = "Latitudine";
            this.longitude = "Longitudine";
            this.localTime = "Ora locale";
            return;
        }
        if (lang.equals(new Language("nl"))) {
            this.daylightSavings = "Zomertijd";
            this.auto = "Automatisch";
            this.manual = "Niet Automatisch";
            this.northLetter = "N";
            this.southLetter = "Z";
            this.eastLetter = "O";
            this.westLetter = "W";
            this.sky = "Hemel";
            this.innerSolarSystem = "Binnenzonnestelsel";
            this.outerSolarSystem = "Buitenzonnestelsel";
            this.update = "Aanpassing";
            this.nakedEyePlanetsOnly = "Enkel blote-oog planeten";
            this.timeZone = "Tijdszone";
            this.monthNames[0] = "jan";
            this.monthNames[3] = "apr";
            this.monthNames[6] = "jul";
            this.monthNames[9] = "okt";
            this.monthNames[1] = "feb";
            this.monthNames[4] = "mei";
            this.monthNames[7] = "aug";
            this.monthNames[10] = "nov";
            this.monthNames[2] = "maa";
            this.monthNames[5] = "jun";
            this.monthNames[8] = "sep";
            this.monthNames[11] = "dec";
            this.planetNames[0] = "Mercurius";
            this.planetNames[3] = "Mars";
            this.planetNames[6] = "Uranus";
            this.planetNames[1] = "Venus";
            this.planetNames[4] = "Jupiter";
            this.planetNames[7] = "Neptunus";
            this.planetNames[2] = "aarde";
            this.planetNames[5] = "Saturnus";
            this.planetNames[8] = "Pluto";
            this.sun = "zon";
            this.moon = "maan";
            this.latitude = "Breedtegraad";
            this.longitude = "Lengtegraad";
            this.localTime = "Lokale tijd";
            return;
        }
        if (lang.equals(new Language("af"))) {
            this.daylightSavings = "Daglig besparing";
            this.auto = "Outomaties";
            this.manual = "Nie Outomaties";
            this.northLetter = "N";
            this.southLetter = "S";
            this.eastLetter = "O";
            this.westLetter = "W";
            this.sky = "Lug";
            this.innerSolarSystem = "Binne sonnestelsel";
            this.outerSolarSystem = "Buite sonnestelsel";
            this.update = "Opdateer";
            this.nakedEyePlanetsOnly = "Blote oog planete aleenlik";
            this.timeZone = "Tyd sone";
            this.monthNames[0] = "Jan";
            this.monthNames[3] = "Apr";
            this.monthNames[6] = "Jul";
            this.monthNames[9] = "Okt";
            this.monthNames[1] = "Feb";
            this.monthNames[4] = "Mei";
            this.monthNames[7] = "Aug";
            this.monthNames[10] = "Nov";
            this.monthNames[2] = "Ma";
            this.monthNames[5] = "Jun";
            this.monthNames[8] = "Sep";
            this.monthNames[11] = "Des";
            this.planetNames[0] = "Merkerius";
            this.planetNames[3] = "Mars";
            this.planetNames[6] = "Uranus";
            this.planetNames[1] = "Venus";
            this.planetNames[4] = "Jupiter";
            this.planetNames[7] = "Neptunus";
            this.planetNames[2] = "Aarde";
            this.planetNames[5] = "Saturnus";
            this.planetNames[8] = "Pluto";
            this.sun = "Son";
            this.moon = "Maan";
            this.latitude = "breedtegraad";
            this.longitude = "Lengtegraad";
            this.localTime = "Lokale tyd";
            return;
        }
        if (lang.equals(new Language("pt"))) {
            this.daylightSavings = "Hor\u00e1rio de Ver\u00e3o";
            this.auto = "Auto";
            this.manual = "Manual";
            this.northLetter = "N";
            this.southLetter = "S";
            this.eastLetter = "L";
            this.westLetter = "O";
            this.sky = "C\u00e9u";
            this.innerSolarSystem = "Sistema Solar Interno";
            this.outerSolarSystem = "Sistema Solar Externo";
            this.update = "Atualizar";
            this.nakedEyePlanetsOnly = "Somente Planetas Vis\u00edveis a Olho N\u00fa";
            this.timeZone = "Fuso Hor\u00e1rio";
            this.monthNames[0] = "Jan";
            this.monthNames[3] = "Abr";
            this.monthNames[6] = "Jul";
            this.monthNames[9] = "Out";
            this.monthNames[1] = "Fev";
            this.monthNames[4] = "Mai";
            this.monthNames[7] = "Ago";
            this.monthNames[10] = "Nov";
            this.monthNames[2] = "Mar";
            this.monthNames[5] = "Jun";
            this.monthNames[8] = "Set";
            this.monthNames[11] = "Dez";
            this.planetNames[0] = "Merc\u00fario";
            this.planetNames[3] = "Marte";
            this.planetNames[6] = "Urano";
            this.planetNames[1] = "Venus";
            this.planetNames[4] = "J\u00fapiter";
            this.planetNames[7] = "Netuno";
            this.planetNames[2] = "Terra";
            this.planetNames[5] = "Saturno";
            this.planetNames[8] = "Plut\u00e3o";
            this.sun = "Sol";
            this.moon = "Lua";
            this.latitude = "Latitude";
            this.longitude = "Longitude";
            this.localTime = "Hora Local";
            return;
        }
        if (lang.equals(new Language("pl"))) {
            this.daylightSavings = "Czas letni";
            this.auto = "Automatycznie";
            this.manual = "R\u0119cznie";
            this.northLetter = "N";
            this.southLetter = "S";
            this.eastLetter = "E";
            this.westLetter = "W";
            this.sky = "Niebo";
            this.innerSolarSystem = "Wewn\u0119trzny Uk\u0142ad S\u0142oneczny";
            this.outerSolarSystem = "Zewn\u0119trzny Uk\u0142ad S\u0142oneczny";
            this.update = "Update";
            this.nakedEyePlanetsOnly = "jedynie planety widoczne go\u0142ym okiem";
            this.timeZone = "Strefa czasowa";
            this.monthNames[0] = "Sty";
            this.monthNames[3] = "Kwi";
            this.monthNames[6] = "Lip";
            this.monthNames[9] = "Pa\u017a";
            this.monthNames[1] = "Lut";
            this.monthNames[4] = "Maj";
            this.monthNames[7] = "Sie";
            this.monthNames[10] = "Lis";
            this.monthNames[2] = "Mar";
            this.monthNames[5] = "Cze";
            this.monthNames[8] = "Wrz";
            this.monthNames[11] = "Gru";
            this.planetNames[0] = "Merkury";
            this.planetNames[3] = "Mars";
            this.planetNames[6] = "Uran";
            this.planetNames[1] = "Wenus";
            this.planetNames[4] = "Jowisz";
            this.planetNames[7] = "Neptun";
            this.planetNames[2] = "Ziemia";
            this.planetNames[5] = "Saturn";
            this.planetNames[8] = "Pluton";
            this.sun = "S\u0142o\u0144ce";
            this.moon = "Ksi\u0119\u017cyc";
            this.latitude = "Szeroko\u015b\u0107";
            this.longitude = "D\u0142ugo\u015b\u0107";
            this.localTime = "Czas lokalny";
            return;
        }
        if (lang.equals(new Language("zh"))) {
            this.daylightSavings = "\u590f\u65f6\u5236\u8c03\u6574";
            this.auto = "\u81ea\u52a8";
            this.manual = "\u624b\u52a8";
            this.northLetter = "\u5317";
            this.southLetter = "\u5357";
            this.eastLetter = "\u4e1c";
            this.westLetter = "\u897f";
            this.sky = "\u5929\u7a7a";
            this.innerSolarSystem = "\u5185\u884c\u661f";
            this.outerSolarSystem = "\u5916\u884c\u661f";
            this.update = "\u66f4\u65b0";
            this.nakedEyePlanetsOnly = "\u53ea\u663e\u793a\u8089\u773c\u53ef\u89c1\u7684\u884c\u661f";
            this.timeZone = "\u65f6\u533a";
            this.monthNames[0] = "\u4e00\u6708";
            this.monthNames[3] = "\u56db\u6708";
            this.monthNames[6] = "\u4e03\u6708";
            this.monthNames[9] = "\u5341\u6708";
            this.monthNames[1] = "\u4e8c\u6708";
            this.monthNames[4] = "\u4e94\u6708";
            this.monthNames[7] = "\u516b\u6708";
            this.monthNames[10] = "\u5341\u4e00\u6708";
            this.monthNames[2] = "\u4e09\u6708";
            this.monthNames[5] = "\u516d\u6708";
            this.monthNames[8] = "\u4e5d\u6708";
            this.monthNames[11] = "\u5341\u4e8c\u6708";
            this.planetNames[0] = "\u6c34\u661f";
            this.planetNames[3] = "\u706b\u661f";
            this.planetNames[6] = "\u5929\u738b\u661f";
            this.planetNames[1] = "\u91d1\u661f";
            this.planetNames[4] = "\u6728\u661f";
            this.planetNames[7] = "\u6d77\u738b\u661f";
            this.planetNames[2] = "\u5730\u7403";
            this.planetNames[5] = "\u571f\u661f";
            this.planetNames[8] = "\u51a5\u738b\u661f";
            this.sun = "\u592a\u9633";
            this.moon = "\u6708\u7403";
            this.latitude = "\u7eac\u5ea6";
            this.longitude = "\u7ecf\u5ea6";
            this.localTime = "\u5f53\u5730\u65f6\u95f4";
            return;
        }
        this.daylightSavings = "Daylight savings";
        this.auto = "Auto";
        this.manual = "Manual";
        this.northLetter = "N";
        this.southLetter = "S";
        this.eastLetter = "E";
        this.westLetter = "W";
        this.sky = "Sky";
        this.innerSolarSystem = "Inner solar system";
        this.outerSolarSystem = "Outer solar system";
        this.update = "Update";
        this.nakedEyePlanetsOnly = "Naked-eye planets only";
        this.timeZone = "Time zone";
        this.monthNames[0] = "Jan";
        this.monthNames[3] = "Apr";
        this.monthNames[6] = "Jul";
        this.monthNames[9] = "Oct";
        this.monthNames[1] = "Feb";
        this.monthNames[4] = "May";
        this.monthNames[7] = "Aug";
        this.monthNames[10] = "Nov";
        this.monthNames[2] = "Mar";
        this.monthNames[5] = "Jun";
        this.monthNames[8] = "Sep";
        this.monthNames[11] = "Dec";
        this.planetNames[0] = "Mercury";
        this.planetNames[3] = "Mars";
        this.planetNames[6] = "Uranus";
        this.planetNames[1] = "Venus";
        this.planetNames[4] = "Jupiter";
        this.planetNames[7] = "Neptune";
        this.planetNames[2] = "Earth";
        this.planetNames[5] = "Saturn";
        this.planetNames[8] = "Pluto";
        this.sun = "Sun";
        this.moon = "Moon";
        this.latitude = "Latitude";
        this.longitude = "Longitude";
        this.localTime = "Local time";
    }
}
