// 
// Decompiled by Procyon v0.5.30
// 

package com.mindprod.jtokens;

import java.awt.Color;

public final class TokenColourScheme
{
    static final long serialVersionUID = 4L;
    public static final Color CSV_FOREGROUND_FOR_COMMENT;
    public static final Color FOREGROUND_FOR_ANNOTATION;
    public static final Color FOREGROUND_FOR_BAT_COMMENT;
    public static final Color FOREGROUND_FOR_BAT_TEXT;
    public static final Color FOREGROUND_FOR_BINARY_HIGH;
    public static final Color FOREGROUND_FOR_BINARY_LOW;
    public static final Color FOREGROUND_FOR_CCONSTANT;
    public static final Color FOREGROUND_FOR_CDATA_CONTENTS;
    public static final Color FOREGROUND_FOR_CDATA_TAG;
    public static final Color FOREGROUND_FOR_CHAR_LITERAL;
    public static final Color FOREGROUND_FOR_CLASSNAME;
    public static final Color FOREGROUND_FOR_COMMENT;
    public static final Color FOREGROUND_FOR_COMMENT_SLASH_SLASH;
    public static final Color FOREGROUND_FOR_COMMENT_SLASH_STAR;
    public static final Color FOREGROUND_FOR_CSV_ITEM;
    public static final Color FOREGROUND_FOR_DECIMAL_ENTITY;
    public static final Color FOREGROUND_FOR_DECIMAL_HIGH;
    public static final Color FOREGROUND_FOR_DECIMAL_LOW;
    public static final Color FOREGROUND_FOR_DIV_OPERATOR;
    public static final Color FOREGROUND_FOR_DOMAIN;
    public static final Color FOREGROUND_FOR_FENCE_BRACE;
    public static final Color FOREGROUND_FOR_FENCE_BRACKET;
    public static final Color FOREGROUND_FOR_FENCE_PAREN;
    public static final Color FOREGROUND_FOR_FILENAME;
    public static final Color FOREGROUND_FOR_GIBBERISH;
    public static final Color FOREGROUND_FOR_HEX_HIGH;
    public static final Color FOREGROUND_FOR_HEX_LOW;
    public static final Color FOREGROUND_FOR_HTML_ALPHA_ENTITY;
    public static final Color FOREGROUND_FOR_HTML_ATTRIBUTE;
    public static final Color FOREGROUND_FOR_HTML_COMMENT_CONTENTS;
    public static final Color FOREGROUND_FOR_HTML_COMMENT_TAG;
    public static final Color FOREGROUND_FOR_HTML_HEX_ENTITY;
    public static final Color FOREGROUND_FOR_HTML_HTML_TAG;
    public static final Color FOREGROUND_FOR_HTML_STRING_LITERAL;
    public static final Color FOREGROUND_FOR_HTML_TEXT;
    public static final Color FOREGROUND_FOR_HTML_UNKNOWN_ENTITY;
    public static final Color FOREGROUND_FOR_HTTP;
    public static final Color FOREGROUND_FOR_HTTP_KEY;
    public static final Color FOREGROUND_FOR_IMPORTANT_KEYWORD;
    public static final Color FOREGROUND_FOR_INI_KEYWORD;
    public static final Color FOREGROUND_FOR_INI_SECTION;
    public static final Color FOREGROUND_FOR_INI_VALUE;
    public static final Color FOREGROUND_FOR_INTERFACE_NAME;
    public static final Color FOREGROUND_FOR_JAVA_VAR;
    public static final Color FOREGROUND_FOR_KEYWORD;
    public static final Color FOREGROUND_FOR_LABEL;
    public static final Color FOREGROUND_FOR_LINE_NUMBER;
    public static final Color FOREGROUND_FOR_METHOD;
    public static final Color FOREGROUND_FOR_NUMERIC_HIGH;
    public static final Color FOREGROUND_FOR_NUMERIC_INDICATOR;
    public static final Color FOREGROUND_FOR_NUMERIC_LITERAL;
    public static final Color FOREGROUND_FOR_NUMERIC_LOW;
    public static final Color FOREGROUND_FOR_OCTAL_HIGH;
    public static final Color FOREGROUND_FOR_OCTAL_LOW;
    public static final Color FOREGROUND_FOR_OPERATOR;
    public static final Color FOREGROUND_FOR_PACKAGE;
    public static final Color FOREGROUND_FOR_PROP_VALUE;
    public static final Color FOREGROUND_FOR_SEMICOLON;
    public static final Color FOREGROUND_FOR_SEPARATOR;
    public static final Color FOREGROUND_FOR_SQL_VAR;
    public static final Color FOREGROUND_FOR_STRING_LITERAL;
    public static final Color FOREGROUND_FOR_TEXT_LINE;
    public static final Color FOREGROUND_FOR_TIMESTAMP;
    public static final Color FOREGROUND_FOR_UNICODE_LITERAL;
    public static final Color INI_FOREGROUND_FOR_COMMENT;
    public static final Color JAVADOC_FOREGROUND_FOR_COMMENT;
    public static final Color PROP_FOREGROUND_FOR_COMMENT;
    public static final Color PROP_FOREGROUND_FOR_KEYWORD;
    
    static {
        CSV_FOREGROUND_FOR_COMMENT = TokenPalette.TWINKLY_GREEN;
        FOREGROUND_FOR_ANNOTATION = TokenPalette.DARK_ECLIPSE_BLUE;
        FOREGROUND_FOR_BAT_COMMENT = TokenPalette.TWINKLY_GREEN;
        FOREGROUND_FOR_BAT_TEXT = TokenPalette.DOG_BROWN;
        FOREGROUND_FOR_BINARY_HIGH = TokenPalette.RHODODENDRON;
        FOREGROUND_FOR_BINARY_LOW = TokenPalette.WINTER_GRAPE;
        FOREGROUND_FOR_CCONSTANT = TokenPalette.FIREBRICK;
        FOREGROUND_FOR_CDATA_CONTENTS = TokenPalette.AGED_WINE;
        FOREGROUND_FOR_CDATA_TAG = TokenPalette.UNOBTRUSIVE_GREY;
        FOREGROUND_FOR_CHAR_LITERAL = TokenPalette.FIERY_RED;
        FOREGROUND_FOR_CLASSNAME = TokenPalette.GREYED_BROWN;
        FOREGROUND_FOR_COMMENT = TokenPalette.TWINKLY_GREEN;
        FOREGROUND_FOR_COMMENT_SLASH_SLASH = TokenPalette.CONSERVATIVE_GREEN;
        FOREGROUND_FOR_COMMENT_SLASH_STAR = TokenPalette.BLUE_TINGED_GREEN;
        FOREGROUND_FOR_CSV_ITEM = TokenPalette.DARK_BLUE;
        FOREGROUND_FOR_DECIMAL_ENTITY = TokenPalette.DARK_OCEAN;
        FOREGROUND_FOR_DECIMAL_HIGH = TokenPalette.WAGON_RED;
        FOREGROUND_FOR_DECIMAL_LOW = TokenPalette.SCOTTISH_RED;
        FOREGROUND_FOR_DIV_OPERATOR = TokenPalette.DEEP_PINK;
        FOREGROUND_FOR_DOMAIN = TokenPalette.CLOTTED_BLOOD;
        FOREGROUND_FOR_FENCE_BRACE = TokenPalette.DARK_CRAYON_BLUE;
        FOREGROUND_FOR_FENCE_BRACKET = TokenPalette.WELCHES;
        FOREGROUND_FOR_FENCE_PAREN = TokenPalette.BLACK;
        FOREGROUND_FOR_FILENAME = TokenPalette.DARK_STAIN_BROWN;
        FOREGROUND_FOR_GIBBERISH = TokenPalette.RASPBERRY;
        FOREGROUND_FOR_HEX_HIGH = TokenPalette.HEX_HIGH_PLUM;
        FOREGROUND_FOR_HEX_LOW = TokenPalette.HEX_LOW_PLUM;
        FOREGROUND_FOR_HTML_ALPHA_ENTITY = TokenPalette.DARK_BLUE;
        FOREGROUND_FOR_HTML_ATTRIBUTE = TokenPalette.CORNFLOWER_BLUE;
        FOREGROUND_FOR_HTML_COMMENT_CONTENTS = TokenPalette.TWINKLY_GREEN;
        FOREGROUND_FOR_HTML_COMMENT_TAG = TokenPalette.UNOBTRUSIVE_GREY;
        FOREGROUND_FOR_HTML_HEX_ENTITY = TokenPalette.INDUSTRIAL_BLUE;
        FOREGROUND_FOR_HTML_HTML_TAG = TokenPalette.MEDIUM_BLUE;
        FOREGROUND_FOR_HTML_STRING_LITERAL = TokenPalette.FIREBRICK;
        FOREGROUND_FOR_HTML_TEXT = TokenPalette.DOG_BROWN;
        FOREGROUND_FOR_HTML_UNKNOWN_ENTITY = TokenPalette.RASPBERRY;
        FOREGROUND_FOR_HTTP = TokenPalette.PERKY_BLUE;
        FOREGROUND_FOR_HTTP_KEY = TokenPalette.DARK_OCEAN;
        FOREGROUND_FOR_IMPORTANT_KEYWORD = TokenPalette.HAPPY_BLUE;
        FOREGROUND_FOR_INI_KEYWORD = TokenPalette.DARK_OCEAN;
        FOREGROUND_FOR_INI_SECTION = TokenPalette.FIREBRICK;
        FOREGROUND_FOR_INI_VALUE = TokenPalette.BLACK;
        FOREGROUND_FOR_INTERFACE_NAME = TokenPalette.GREYED_BROWN;
        FOREGROUND_FOR_JAVA_VAR = TokenPalette.DARK_CYAN;
        FOREGROUND_FOR_KEYWORD = TokenPalette.GREY_19;
        FOREGROUND_FOR_LABEL = TokenPalette.GREYED_BROWN;
        FOREGROUND_FOR_LINE_NUMBER = TokenPalette.DARK_SILVER;
        FOREGROUND_FOR_METHOD = TokenPalette.DARK_BLUE;
        FOREGROUND_FOR_NUMERIC_HIGH = TokenPalette.WAGON_RED;
        FOREGROUND_FOR_NUMERIC_INDICATOR = TokenPalette.TOMATO;
        FOREGROUND_FOR_NUMERIC_LITERAL = TokenPalette.SCOTTISH_RED;
        FOREGROUND_FOR_NUMERIC_LOW = TokenPalette.SCOTTISH_RED;
        FOREGROUND_FOR_OCTAL_HIGH = TokenPalette.RHODODENDRON;
        FOREGROUND_FOR_OCTAL_LOW = TokenPalette.WINTER_GRAPE;
        FOREGROUND_FOR_OPERATOR = TokenPalette.DARK_GREEN;
        FOREGROUND_FOR_PACKAGE = TokenPalette.DOG_BROWN;
        FOREGROUND_FOR_PROP_VALUE = TokenPalette.BLACK;
        FOREGROUND_FOR_SEMICOLON = TokenPalette.WELCHES;
        FOREGROUND_FOR_SEPARATOR = TokenPalette.DARK_GREEN;
        FOREGROUND_FOR_SQL_VAR = TokenPalette.KIWI_BROWN;
        FOREGROUND_FOR_STRING_LITERAL = TokenPalette.FIREPLUG_RED;
        FOREGROUND_FOR_TEXT_LINE = TokenPalette.DARK_CRAYON_BLUE;
        FOREGROUND_FOR_TIMESTAMP = TokenPalette.TARNISHED_GOLD;
        FOREGROUND_FOR_UNICODE_LITERAL = TokenPalette.FIREBRICK;
        INI_FOREGROUND_FOR_COMMENT = TokenPalette.TWINKLY_GREEN;
        JAVADOC_FOREGROUND_FOR_COMMENT = TokenPalette.ECLIPSE_BLUE;
        PROP_FOREGROUND_FOR_COMMENT = TokenPalette.TWINKLY_GREEN;
        PROP_FOREGROUND_FOR_KEYWORD = TokenPalette.DARK_OCEAN;
    }
}
